// syx_to_patches.cpp -- one-time host-only conversion tool (NOT part of the firmware build).
// Converts the 32 real Yamaha reface DX factory-bank .syx bulk-dumps (from the ESP32
// reference project this codebase's FM engine was ported from) into a static C++ table
// for src/presets.cpp. Run manually once; redirect stdout into a file pasted into presets.cpp.
//
// Build: g++ -std=c++17 -I<repo>/include syx_to_patches.cpp -o syx_to_patches
// Run (from the patches/ directory): ./syx_to_patches > out.txt

#include "dx_engine/RDX_Types.h"

#include <cstdio>
#include <cstdint>
#include <vector>

struct FileEntry { const char* path; const char* name; };

static const FileEntry kFiles[32] = {
    {"11-DigiChord_.syx", "DigiChord"},
    {"12-WobbleBass.syx", "WobbleBass"},
    {"13-MotionPad_.syx", "MotionPad"},
    {"14-LegendEP__.syx", "LegendEP"},
    {"15-DynaLead__.syx", "DynaLead"},
    {"16-DarkBass__.syx", "DarkBass"},
    {"17-TublarBell.syx", "TublarBell"},
    {"18-D_n_Beats_.syx", "D_n_Beats"},
    {"21-BeginSweep.syx", "BeginSweep"},
    {"22-MoDemLead_.syx", "MoDemLead"},
    {"23-BeepBass__.syx", "BeepBass"},
    {"24-BitTune___.syx", "BitTune"},
    {"25-TinPerc___.syx", "TinPerc"},
    {"26-BleepClv__.syx", "BleepClv"},
    {"27-FeelIt____.syx", "FeelIt"},
    {"28-BuzzSiren_.syx", "BuzzSiren"},
    {"31-WoodEP____.syx", "WoodEP"},
    {"32-UniLead___.syx", "UniLead"},
    {"33-AttackBass.syx", "AttackBass"},
    {"34-CloudPad__.syx", "CloudPad"},
    {"35-AmbiPluck_.syx", "AmbiPluck"},
    {"36-Marimba___.syx", "Marimba"},
    {"37-CheezOrgan.syx", "CheezOrgan"},
    {"38-FM_Brass__.syx", "FM_Brass"},
    {"41-SolPhase__.syx", "SolPhase"},
    {"42-FlyingKode.syx", "FlyingKode"},
    {"43-AlTiPad___.syx", "AlTiPad"},
    {"44-StarPad___.syx", "StarPad"},
    {"45-WarmPad___.syx", "WarmPad"},
    {"46-FutureBell.syx", "FutureBell"},
    {"47-GlassHarp_.syx", "GlassHarp"},
    {"48-Chopper___.syx", "Chopper"}
};

int main() {
    std::printf("// Generated by syx_to_patches.cpp from tools/refacedx/RDX-Reface-DX-emu/RDX/data/patches/*.syx -- do not hand-edit.\n");

    for (const auto& e : kFiles) {
        std::FILE* f = std::fopen(e.path, "rb");
        if (!f) {
            std::fprintf(stderr, "error: cannot open '%s'\n", e.path);
            return 1;
        }
        std::vector<uint8_t> buf;
        uint8_t tmp[4096];
        size_t n;
        while ((n = std::fread(tmp, 1, sizeof(tmp), f)) > 0) {
            buf.insert(buf.end(), tmp, tmp + n);
        }
        std::fclose(f);

        RDX_Patch patch{};
        if (!syxToPatch(buf.data(), (uint32_t)buf.size(), patch)) {
            std::fprintf(stderr, "error: syxToPatch failed for '%s'\n", e.path);
            return 1;
        }

        const uint8_t* bytes = reinterpret_cast<const uint8_t*>(&patch);
        const size_t sz = sizeof(RDX_Patch);
        std::printf("    { \"%s\", patchFromBytes({", e.name);
        for (size_t i = 0; i < sz; ++i) {
            if (i) std::printf(",");
            std::printf("0x%02X", bytes[i]);
        }
        std::printf("}) },\n");
    }
    return 0;
}
