// J6_Display.cpp — PicoFaceCP-style page renderer + blocking boot splash.
// Page renderer only paints into the u8g2 full buffer; it MUST NOT call
// u8g2_SendBuffer/FirstPage/NextPage (the main loop streams the buffer out in
// staged half-tile rows via g_ui_flush_row). Only the boot-time splash may block.
// Generated by glm-5.2:cloud, formally reviewed by the orchestrator.
#include "J6_Display.h"
#include "j6_logo.h"

void j6_display_splash(u8g2_t* u) {
    u8g2_ClearBuffer(u);
    u8g2_SetBitmapMode(u, false);
    u8g2_DrawXBMP(u, 0, 0, j6_logoWidth, j6_logoHeight, j6_logo);
    // Blocking send is fine here: audio engine is not running yet.
    u8g2_SendBuffer(u);
}

void j6_display_page(u8g2_t* u, const J6UiModel& m) {
    u8g2_ClearBuffer(u);

    // Header: inverted bar with title (left) and page indicator (right).
    u8g2_SetFontPosBaseline(u);
    u8g2_SetFont(u, u8g2_font_8x13B_tf);
    int hasc = u8g2_GetAscent(u);
    int hdesc = u8g2_GetDescent(u);

    u8g2_SetDrawColor(u, 1);
    u8g2_DrawBox(u, 0, 0, 128, hasc - hdesc);
    u8g2_SetDrawColor(u, 0);

    if (m.title[0] != 0) {
        u8g2_DrawStr(u, 2, hasc, m.title);
    }
    if (m.page[0] != 0) {
        int pw = u8g2_GetStrWidth(u, m.page);
        u8g2_DrawStr(u, 126 - pw, hasc, m.page);
    }

    u8g2_SetDrawColor(u, 1);
    u8g2_DrawHLine(u, 0, hasc - hdesc, 128);

    // Body lines: font 8x13B at (4,32) and (4,48).
    u8g2_SetFont(u, u8g2_font_8x13B_tf);
    if (m.lineA[0] != 0) {
        u8g2_DrawStr(u, 4, 32, m.lineA);
    }
    if (m.lineB[0] != 0) {
        u8g2_DrawStr(u, 4, 48, m.lineB);
    }

    // Footer: font 6x10 at (4,62).
    u8g2_SetFont(u, u8g2_font_6x10_tf);
    if (m.footer[0] != 0) {
        u8g2_DrawStr(u, 4, 62, m.footer);
    }

    // Leave state deterministic for the next pass.
    u8g2_SetDrawColor(u, 1);
    u8g2_SetFont(u, u8g2_font_8x13B_tf);

    // NO SendBuffer here: the main loop streams the buffer out in staged
    // half-tile rows via g_ui_flush_row while audio renders on core 0.
}

// Three rows plus a cursor: the section menu and the preset list. Same header
// and footer as j6_display_page, so switching between the two layouts does not
// make the screen jump.
//
// Rows sit at y=25/38/51 with a 13 px pitch, which clears the header bar
// (0..13) and leaves the footer baseline at 62 alone. The selected row is drawn
// white-on-black rather than marked with a ">": at this size an inverted bar is
// legible across a room, a caret is not.
void j6_display_list(u8g2_t* u, const J6ListModel& m) {
    u8g2_ClearBuffer(u);

    u8g2_SetFontPosBaseline(u);
    u8g2_SetFont(u, u8g2_font_8x13B_tf);
    int hasc = u8g2_GetAscent(u);
    int hdesc = u8g2_GetDescent(u);

    u8g2_SetDrawColor(u, 1);
    u8g2_DrawBox(u, 0, 0, 128, hasc - hdesc);
    u8g2_SetDrawColor(u, 0);

    if (m.title[0] != 0) {
        u8g2_DrawStr(u, 2, hasc, m.title);
    }
    if (m.page[0] != 0) {
        int pw = u8g2_GetStrWidth(u, m.page);
        u8g2_DrawStr(u, 126 - pw, hasc, m.page);
    }

    u8g2_SetDrawColor(u, 1);
    u8g2_DrawHLine(u, 0, hasc - hdesc, 128);

    u8g2_SetFont(u, u8g2_font_7x13B_tf);
    for (int i = 0; i < 3; ++i) {
        if (m.rows[i][0] == 0) continue;

        const int baseline = 25 + i * 13;
        if (i == m.cursor) {
            u8g2_SetDrawColor(u, 1);
            u8g2_DrawBox(u, 0, baseline - 10, 128, 13);
            u8g2_SetDrawColor(u, 0);
        } else {
            u8g2_SetDrawColor(u, 1);
        }
        u8g2_DrawStr(u, 3, baseline, m.rows[i]);
    }

    u8g2_SetDrawColor(u, 1);
    u8g2_SetFont(u, u8g2_font_6x10_tf);
    if (m.footer[0] != 0) {
        u8g2_DrawStr(u, 4, 62, m.footer);
    }

    // Leave state deterministic for the next pass.
    u8g2_SetDrawColor(u, 1);
    u8g2_SetFont(u, u8g2_font_8x13B_tf);

    // NO SendBuffer here: same staged flush as j6_display_page.
}
