// SM_Display.h — Pure-visual display module for PicoFaceSM (RP2350 + SH1106 128x64 via u8g2 C-API).
// Mirrors the PicoFaceCP look: inverted header bar + separator, page indicator,
// body lines and footer. Content strings are preformatted by the caller (rd_main.cpp).
// Generated by glm-5.2:cloud, formally reviewed by the orchestrator.
#pragma once
#include <stdint.h>
#include "u8g2.h"

struct SmUiModel {
    char title[16];   // header left, e.g. "PATCH 32k"
    char page[8];     // header right, e.g. "1/5"
    char lineA[26];   // body line at y=32 (font 8x13B)
    char lineB[26];   // body line at y=48 (font 8x13B)
    char footer[26];  // footer at y=62 (font 6x10), diagnostics
};

void sm_display_splash(u8g2_t* u); // boot only: draws logo + BLOCKING SendBuffer
void sm_display_page(u8g2_t* u, const SmUiModel& m); // draws into buffer, NO send
