# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Michi71
"""Turns the 16 descriptor packs into what the firmware embeds.

    rd_embed_packs.py [--model=BOTH|MKS20|MK80] <in_dir> <out_dir>

Writes into <out_dir>:
    rd_packs.bin        the sixteen packs, concatenated
    rd_packs_blob.S     assembly that pulls it in with .incbin
    rd_packs_tables.cpp rd_pack_ptrs / rd_pack_sizes over that blob

The packs are capture output: the reference emulator plays every (patch, note,
velocity) and the analyzer distills the firmware's register writes into note
descriptors. They are derived from Roland's ROMs and are no more distributable
than the ROMs are, so they live in instruments/PicoFaceRD/roms/ beside them and
neither is in this repository.

An earlier version of this script emitted the packs as C initialiser lists. The
result was a 20 MB source file that the compiler took minutes to chew through,
for data it then laid down verbatim. .incbin does the same job in no time.
"""
import os
import sys

# Patches 0-7 are the MKS-20's, 8-15 the MK-80's -- the split the machines
# themselves make, and the one the patch names already carry. A single-machine
# build ships one half, which is what lets PicoFaceRD fit a 4 MB Pico 2.
PATCHES = {"BOTH": range(16), "MKS20": range(0, 8), "MK80": range(8, 16)}

BLOB_S = """/* Generated by tools/rd_extract/rd_embed_packs.py -- do not edit.
   .S so the preprocessor runs first: this assembles both for the firmware
   (ELF, bare symbol names) and for the host harness (Mach-O, underscored). */
#ifdef __APPLE__
#define RDSYM(x) _##x
    .section __TEXT,__const
#else
#define RDSYM(x) x
    .section .rodata.rd_packs, "a"
#endif
    .balign 4
    .global RDSYM(rd_pack_blob)
RDSYM(rd_pack_blob):
    .incbin "{blob}"
"""


def main():
    argv = sys.argv[1:]
    model = "BOTH"
    if argv and argv[0].startswith("--model="):
        model = argv.pop(0).split("=", 1)[1].upper()
    if model not in PATCHES:
        print(f"rd_embed_packs: unknown model {model}, "
              f"expected one of {', '.join(PATCHES)}", file=sys.stderr)
        sys.exit(1)
    if len(argv) != 2:
        print("usage: rd_embed_packs.py [--model=BOTH|MKS20|MK80] "
              "<in_dir> <out_dir>", file=sys.stderr)
        sys.exit(1)
    in_dir, out_dir = argv[0], argv[1]
    patches = list(PATCHES[model])
    os.makedirs(out_dir, exist_ok=True)

    sizes, blob = [], bytearray()
    for i in patches:
        path = os.path.join(in_dir, f"pack_p{i}.rdp")
        if not os.path.exists(path):
            print(f"rd_embed_packs: missing {path}", file=sys.stderr)
            sys.exit(1)
        with open(path, "rb") as f:
            data = f.read()
        sizes.append(len(data))
        blob += data
        # Each pack starts on a four-byte boundary: the engine reads 32-bit
        # fields straight out of it.
        while len(blob) % 4:
            blob += b"\0"

    blob_path = os.path.join(out_dir, "rd_packs.bin")
    with open(blob_path, "wb") as f:
        f.write(blob)
    with open(os.path.join(out_dir, "rd_packs_blob.S"), "w") as f:
        f.write(BLOB_S.format(blob=blob_path))

    offs, at = [], 0
    for n in sizes:
        offs.append(at)
        at += n + (-n % 4)

    lines = ['// Generated by tools/rd_extract/rd_embed_packs.py -- do not edit.',
             '#include "rd_packs_data.h"', '',
             'extern "C" const uint8_t rd_pack_blob[];', '',
             f'const uint8_t* const rd_pack_ptrs[{len(patches)}] = {{']
    lines += [f"    rd_pack_blob + {o}," for o in offs]
    lines += ['};', '', f'const size_t rd_pack_sizes[{len(patches)}] = {{']
    lines += [f"    {n}," for n in sizes]
    lines += ['};', '']
    with open(os.path.join(out_dir, "rd_packs_tables.cpp"), "w") as f:
        f.write("\n".join(lines))

    print(f"rd_embed_packs: {model}, {sum(sizes)} bytes in "
          f"{len(patches)} packs -> {blob_path}")


if __name__ == "__main__":
    main()
