# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Michi71
"""Turns a local MKS-20 / MK-80 ROM set into the blob PicoFaceRD embeds.

    rd_make_rom.py <romdir> <out.blob> [ilv.bin]

Replaces rd_make_rom.sh and its C++ helper, which had to compile and link a
checkout of the reference emulator to get at the descrambling. rd_descramble.py
does that in Python now, so **the build needs no emulator at all**.

The two lookup tables the engine wants alongside the sample banks are not read
from any ROM -- the sound chip computes them from its own arithmetic, and they
are the same on every machine. Rather than transcribe a hundred lines of
silicon-derived boolean logic to recompute constants, they are stored beside
this file as rd_chip_tables.bin.xz, 27 KB, the same way rd_new_engine.cpp
already carries the chip's envelope table.

What comes out is what the firmware reads: three packed sample banks and those
two tables. The decoded exponent/delta arrays, the parameter ROM and the
program ROM stay on the host -- only the firmware analysis wants those, and
rd_unscramble writes them.
"""
import lzma
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rd_descramble  # noqa: E402

BANK = 0x20000
TABLES = "rd_chip_tables.bin.xz"

# Which dump is which chip. Established by reproducing the tables this
# instrument shipped until now, byte for byte, for all three models.
MODELS = (("a", "mks20_15179738.BIN", "mks20_15179737.BIN", "mks20_15179736.BIN"),
          ("b", "mks20_15179741.BIN", "mks20_15179740.BIN", "mks20_15179739.BIN"),
          ("m", "MK80_IC5.bin", "MK80_IC6.bin", "MK80_IC7.bin"))


def pack(exp, exp_sign, delta, delta_sign):
    """One 32-bit word a sample: four bytes in one XIP burst rather than four
    scattered reads. Layout is gen_pk4's, unchanged."""
    return ((exp & 0x3FFF)
            | ((1 if exp_sign else 0) << 14)
            | ((delta & 0x01FF) << 15)
            | ((1 if delta_sign else 0) << 24))


def read_rom(directory, name, size):
    path = os.path.join(directory, name)
    try:
        data = open(path, "rb").read()
    except OSError:
        sys.stderr.write(f"rd_make_rom: cannot open {path}\n")
        sys.exit(2)
    if len(data) != size:
        sys.stderr.write(f"rd_make_rom: {path} is {len(data)} bytes, "
                         f"expected {size}\n")
        sys.exit(2)
    return data


def main():
    if len(sys.argv) not in (3, 4):
        sys.stderr.write("usage: rd_make_rom.py <romdir> <out.blob> [ilv.bin]\n")
        sys.exit(1)
    romdir, outpath = sys.argv[1], sys.argv[2]
    ilvpath = sys.argv[3] if len(sys.argv) == 4 else None

    blob = bytearray()
    ilv = bytearray()
    for tag, a, b, c in MODELS:
        raw = [read_rom(romdir, n, BANK) for n in (a, b, c)]
        exp, exp_sign, delta, delta_sign = rd_descramble.sample_bank(*raw)
        words = [pack(exp[i], exp_sign[i], delta[i], delta_sign[i])
                 for i in range(BANK)]
        blob += struct.pack(f"<{BANK}I", *words)
        if ilvpath:
            # The same samples spread over eight bytes, which is what the
            # reference emulator's own arrays look like. Only the A/B
            # regression wants this; the firmware reads the packed form.
            for i in range(BANK):
                ilv += struct.pack("<HHBBH", exp[i], delta[i],
                                   1 if exp_sign[i] else 0,
                                   1 if delta_sign[i] else 0, 0)
        print(f"  bank {tag}: {a} / {b} / {c}")

    tables = lzma.decompress(
        open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          TABLES), "rb").read())
    blob += tables
    print("  tables: phase_exp, samples_exp")

    open(outpath, "wb").write(blob)
    print(f"rd_make_rom: {len(blob)} bytes -> {outpath}")

    # The assembly beside it. Offsets never move, but .incbin needs a literal
    # path, so it is written here rather than checked in. Two files: anything
    # linking against the reference emulator must take the sample banks without
    # the tables, which that emulator computes itself.
    base = outpath[:-5] if outpath.endswith(".blob") else outpath
    prologue = ('#ifdef __APPLE__\n#define RDSYM(x) _##x\n'
                '#else\n#define RDSYM(x) x\n#endif\n')
    def section(name):
        return ('#ifdef __APPLE__\n    .section __TEXT,__const\n'
                f'#else\n    .section {name}, "a"\n#endif\n')
    with open(base + "_blob.S", "w") as f:
        f.write("/* Generated by tools/rd_extract/rd_make_rom.py -- do not edit. */\n")
        f.write(prologue + section(".rodata.rd_rom") + "    .balign 8\n")
        for i, sym in enumerate(("rd_samples_pk4_a", "rd_samples_pk4_b",
                                 "rd_samples_pk4_m")):
            f.write(f"    .global RDSYM({sym})\nRDSYM({sym}):\n"
                    f'    .incbin "{outpath}", {i * BANK * 4}, {BANK * 4}\n')
    with open(base + "_tables.S", "w") as f:
        f.write("/* Generated by tools/rd_extract/rd_make_rom.py -- do not edit.\n"
                "   Omit when linking against the reference emulator, which\n"
                "   computes these two itself. */\n")
        f.write(prologue + section(".rodata.rd_rom_tables") + "    .balign 4\n")
        off = 3 * BANK * 4
        f.write(f'    .global RDSYM(rd_phase_exp_table)\nRDSYM(rd_phase_exp_table):\n'
                f'    .incbin "{outpath}", {off}, 262144\n')
        f.write(f'    .global RDSYM(rd_samples_exp_table)\nRDSYM(rd_samples_exp_table):\n'
                f'    .incbin "{outpath}", {off + 262144}, 65536\n')
    print(f"rd_make_rom: {base}_blob.S, {base}_tables.S")

    if ilvpath:
        open(ilvpath, "wb").write(ilv)
        ilvbase = ilvpath[:-4] if ilvpath.endswith(".bin") else ilvpath
        with open(ilvbase + ".S", "w") as f:
            f.write("/* Generated by tools/rd_extract/rd_make_rom.py -- do not edit. */\n")
            f.write(prologue + section(".rodata.rd_ilv") + "    .balign 8\n")
            for i, sym in enumerate(("rd_samples_ilv_a", "rd_samples_ilv_b",
                                     "rd_samples_ilv_m")):
                f.write(f"    .global RDSYM({sym})\nRDSYM({sym}):\n"
                        f'    .incbin "{ilvpath}", {i * BANK * 8}, {BANK * 8}\n')
        print(f"rd_make_rom: {len(ilv)} bytes -> {ilvpath}, {ilvbase}.S")


if __name__ == "__main__":
    main()
