#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Michi71
#
# Builds and runs rd_make_rom: ROM set -> the blob PicoFaceRD embeds.
#
#   RDPIANO=/path/to/rdpiano rd_make_rom.sh <romdir> <out.blob>
#
# RDPIANO points at a checkout of the reference emulator (Michi71/rdpiano or
# giulioz/rdpiano). It is read, never written, and never copied into this
# repository -- what happens here is a hooked copy in a scratch directory,
# with the sample arrays made reachable so they can be read out. The emulator
# is GPL-3, as is this repository; see instruments/PicoFaceRD/README.md.

set -euo pipefail

if [ $# -lt 2 ] || [ $# -gt 3 ]; then
    echo "usage: RDPIANO=/path/to/rdpiano $0 <romdir> <out.blob> [ilv.bin]" >&2
    exit 1
fi
romdir=$1
outblob=$2
outilv=${3:-}

if [ -z "${RDPIANO:-}" ]; then
    echo "$0: set RDPIANO to a checkout of the reference emulator" >&2
    echo "    git clone https://github.com/Michi71/rdpiano" >&2
    exit 1
fi

# Both layouts seen in the wild: the standalone library and the full project.
#
# It has to be the *upstream* emulator, the one whose SoundChip takes three ROM
# images. The adapted copy used by the A/B test takes a model index and reads
# from tables compiled into it -- exactly the tables this script exists to stop
# needing, so it cannot be the source of them.
for cand in "$RDPIANO/librdpiano" "$RDPIANO/rdpiano" "$RDPIANO"; do
    if [ -f "$cand/src/sound_chip.cpp" ] && [ -f "$cand/include/sound_chip.h" ]; then
        upstream=$cand
        break
    fi
done
if [ -z "${upstream:-}" ]; then
    echo "$0: no src/sound_chip.cpp under $RDPIANO" >&2
    exit 1
fi
if ! grep -q 'SoundChip(const u8 \*' "$upstream/include/sound_chip.h"; then
    echo "$0: $upstream is the adapted emulator (SoundChip takes a model index)." >&2
    echo "    This needs the upstream one, which takes the three ROM images:" >&2
    echo "    git clone https://github.com/Michi71/rdpiano" >&2
    exit 1
fi

here=$(cd "$(dirname "$0")" && pwd)
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/include" "$work/src"

# The one change: the sample arrays are private, and this tool has to read
# them. Nothing else about the emulator is touched.
sed 's/^private:/public:/' "$upstream/include/sound_chip.h" > "$work/include/sound_chip.h"
cp "$upstream/include/mame_utils.h" "$work/include/"
cp "$upstream/src/sound_chip.cpp"   "$work/src/"

echo "rd_make_rom: building against $upstream"
c++ -O2 -w -std=c++17 -I "$work/include" -o "$work/rd_make_rom" \
    "$here/rd_make_rom.cpp" "$work/src/sound_chip.cpp"

"$work/rd_make_rom" "$romdir" "$outblob" ${outilv:+"$outilv"}

# The interleaved banks get their own assembly, for the capture harness only.
if [ -n "$outilv" ]; then
    cat > "${outilv%.bin}.S" <<ASM
/* Generated by tools/rd_extract/rd_make_rom.sh -- do not edit. */
#ifdef __APPLE__
#define RDSYM(x) _##x
    .section __TEXT,__const
#else
#define RDSYM(x) x
    .section .rodata.rd_ilv, "a"
#endif
    .balign 8
    .global RDSYM(rd_samples_ilv_a)
RDSYM(rd_samples_ilv_a):
    .incbin "$outilv", 0, 1048576
    .global RDSYM(rd_samples_ilv_b)
RDSYM(rd_samples_ilv_b):
    .incbin "$outilv", 1048576, 1048576
    .global RDSYM(rd_samples_ilv_m)
RDSYM(rd_samples_ilv_m):
    .incbin "$outilv", 2097152, 1048576
ASM
    echo "rd_make_rom: ${outilv%.bin}.S"
fi

# The assembly beside it. Offsets are the blob's layout and never move, but
# .incbin needs a literal path, so it is written here rather than checked in.
#
# Two files, not one: the reference emulator computes the same two lookup
# tables itself, so anything that links against it must take the sample banks
# without them or the symbols collide. The firmware takes both.
base="${outblob%.blob}"

# .S rather than .s: the compiler driver runs it through the preprocessor, and
# it has to assemble for two targets. The firmware is ELF and wants bare symbol
# names; the host harness is Mach-O on this machine and wants them underscored.
prologue='#ifdef __APPLE__
#define RDSYM(x) _##x
#else
#define RDSYM(x) x
#endif'

cat > "${base}_blob.S" <<ASM
/* Generated by tools/rd_extract/rd_make_rom.sh -- do not edit.
   The three packed sample banks, named at their offsets in the blob. Symbols
   rather than pointers, so the engine indexes plain arrays. */
$prologue
#ifdef __APPLE__
    .section __TEXT,__const
#else
    .section .rodata.rd_rom, "a"
#endif
    .balign 8
    .global RDSYM(rd_samples_pk4_a)
RDSYM(rd_samples_pk4_a):
    .incbin "$outblob", 0, 524288
    .global RDSYM(rd_samples_pk4_b)
RDSYM(rd_samples_pk4_b):
    .incbin "$outblob", 524288, 524288
    .global RDSYM(rd_samples_pk4_m)
RDSYM(rd_samples_pk4_m):
    .incbin "$outblob", 1048576, 524288
ASM

cat > "${base}_tables.S" <<ASM
/* Generated by tools/rd_extract/rd_make_rom.sh -- do not edit.
   The chip's two arithmetic tables. Omit this file when linking against the
   reference emulator, which computes them in its own constructor. */
$prologue
#ifdef __APPLE__
    .section __TEXT,__const
#else
    .section .rodata.rd_rom_tables, "a"
#endif
    .balign 4
    .global RDSYM(rd_phase_exp_table)
RDSYM(rd_phase_exp_table):
    .incbin "$outblob", 1572864, 262144
    .global RDSYM(rd_samples_exp_table)
RDSYM(rd_samples_exp_table):
    .incbin "$outblob", 1835008, 65536
ASM
echo "rd_make_rom: ${base}_blob.S, ${base}_tables.S"
