#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Michi71
# run_regression.sh
# One-command host regression runner for PicoFaceRD.
# Builds two host tools, runs an A/B matrix against the reference emulator,
# runs stuck-voice stress tests, and aggregates a final PASS/FAIL summary.
#
# Usage: RDPIANO=/path/to/rdpiano ./run_regression.sh
#
# Two things it needs that are deliberately not in this repository:
#
#   RDPIANO   a checkout of https://github.com/giulioz/rdpiano -- the reference
#             emulator, in its original state. This is what the A/B test
#             compares the engine against.
#   roms/     instruments/PicoFaceRD/roms/, holding the nine sample ROMs, the
#             two parameter ROMs, RD200_B.bin and the sixteen .rdp packs.
#
# The reference used to be an adapted copy of that emulator, and the difference
# turned out not to be cosmetic: the adaptation carries a hand-written
# per-patch voicing table -- gain, brightness, saturation, noise, ten partials
# each -- which is live in its output path and which the original does not
# have. Measuring against it was measuring the adaptation. Switched 2026-08-26,
# and the expectations below were re-frozen with it.
#
# The adapted copy is still what make_packs.sh drives for the capture path;
# that one wants its loadPatch and its compiled-in tables, and no sound of its
# comes out of it.
#
# The packs used to be dumped back out of a generated source file in the
# instrument tree. They are input now, not output, so that step is gone.
# Generated by glm-5.2:cloud, formally reviewed by the orchestrator.
# Orchestrator fixes: stress FAIL now increments the fail counter, empty
# parse results (tool crash) count as FAIL, dead placeholder loop removed.

set -u

# Two roots, because the move into the collection split what used to be one
# tree: the engine went to instruments/PicoFaceRD/ ($R, still addressed as
# "$R/include" and "$R/src" throughout), while these harnesses went to
# tools/rd_extract/ at the repository root ($HERE). The first version of this
# line kept only $R and left the harness sources under "$R/tools/rd_extract",
# where nothing has been since the merge - so the runner failed on its very
# first build and stayed that way.
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
R="$REPO/instruments/PicoFaceRD"
WORK="$REPO/build_host"
ROMS="$R/roms"
mkdir -p "$WORK"

# Deliberately NOT falling back to RDPIANO_REF: that names the adapted copy,
# and silently measuring against it is the mistake this switch removes.
if [ -z "${RDPIANO:-}" ]; then
    echo "run_regression: set RDPIANO to a checkout of the reference emulator" >&2
    echo "    git clone https://github.com/giulioz/rdpiano" >&2
    exit 1
fi
REF="$RDPIANO"
RD=""
for cand in "$REF/rdpiano" "$REF/librdpiano" "$REF"; do
    if [ -f "$cand/src/mcu.cpp" ] && [ -f "$cand/include/mcu.h" ]; then RD="$cand"; break; fi
done
if [ -z "$RD" ]; then
    echo "run_regression: no src/mcu.cpp under $REF" >&2
    exit 1
fi
# Two checks that the checkout really is the reference and not an adaptation
# of it. The first is the API the A/B test is written against; the second is
# the reason this matters at all.
if ! grep -q 'generate_next_sample' "$RD/include/mcu.h"; then
    echo "run_regression: $RD is not the reference emulator -- its Mcu has no" >&2
    echo "    generate_next_sample. An adapted copy will not do here:" >&2
    echo "    git clone https://github.com/giulioz/rdpiano" >&2
    exit 1
fi
if grep -q 'g_voicingTable' "$RD/src/sound_chip.cpp"; then
    echo "run_regression: $RD carries a per-patch voicing table in its sound" >&2
    echo "    path, so it is an adapted copy, not the reference. Measuring" >&2
    echo "    against it would measure the adaptation. Use the original:" >&2
    echo "    git clone https://github.com/giulioz/rdpiano" >&2
    exit 1
fi
if [ ! -f "$ROMS/pack_p0.rdp" ]; then
    echo "run_regression: no ROM set in $ROMS; see instruments/PicoFaceRD/README.md" >&2
    exit 1
fi

# The sample banks the engine reads, built from the ROMs exactly as the
# firmware build does it. The two lookup tables come along this time: the
# reference computes its own privately, so nothing collides.
echo "[prep] sample banks"
python3 "$HERE/rd_make_rom.py" "$ROMS" "$WORK/rd_rom.blob" >/dev/null || {
    echo "[FAIL] rd_make_rom"; exit 1; }
echo "[prep] descriptor packs"
python3 "$HERE/rd_embed_packs.py" "$ROMS" "$WORK" >/dev/null || {
    echo "[FAIL] rd_embed_packs"; exit 1; }

fails=0
total=0

# float compare: arg1=lhs arg2=op arg3=rhs. Returns 0 if expr true.
# Empty lhs (failed parse) is never true -> caller treats it as FAIL.
flt() {
    local lhs="$1"; local op="$2"; local rhs="$3"
    [ -n "$lhs" ] || return 1
    awk -v a="$lhs" -v b="$rhs" -v o="$op" 'BEGIN{
        r=0
        if(o=="<="){ r=(a<=b) }
        else if(o==">="){ r=(a>=b) }
        else if(o=="=="){ r=(a==b) }
        else if(o=="<"){ r=(a<b) }
        else if(o==">"){ r=(a>b) }
        else if(o=="!="){ r=(a!=b) }
        exit(r?0:1)
    }'
}

# Build helper: echoes a [build] line, runs clang++, checks status.
build_tool() {
    local tool="$1"; shift
    echo "[build] $tool"
    if ! "$@"; then
        echo "[FAIL] build $tool"
        exit 1
    fi
}

# 2) Build tools
# The engine's rom_tables.h names the packed sample banks and the chip's two
# lookup tables. The reference emulator has no header of that name -- it
# computes those two itself in its SoundChip constructor -- so the shim just
# carries the engine's declarations, ahead of anything else on the path.
mkdir -p "$WORK/shim"
cat > "$WORK/shim/rom_tables.h" <<'SHIM'
/* Generated by run_regression.sh. */
#pragma once
#include <cstdint>
extern const uint32_t rd_samples_pk4_a[0x20000];
extern const uint32_t rd_samples_pk4_b[0x20000];
extern const uint32_t rd_samples_pk4_m[0x20000];
extern const uint16_t rd_phase_exp_table[131072];
extern const uint16_t rd_samples_exp_table[32768];
SHIM

# The emulator and its model tables come from the checkout; the sample banks
# from the blob just built. rd_rom_tables.S is left out on purpose here -- the
# emulator's program_tables.cpp already defines those two.
build_tool rd_ab_test \
    clang++ -O2 -w -std=c++17 -I "$WORK/shim" -I "$RD/include" \
        -I "$R/include" -I "$R/include/rd_engine" \
    -o "$WORK/rd_ab_test" \
    "$HERE/rd_ab_test.cpp" \
    "$RD/src/mcu.cpp" \
    "$RD/src/sound_chip.cpp" \
    "$R/src/rd_engine/rd_new_engine.cpp" \
    "$WORK/rd_rom_blob.S" \
    "$WORK/rd_rom_tables.S"

build_tool rd_stress2 \
    clang++ -O2 -w -std=c++17 -I "$R/include" -I "$R/include/rd_engine" -I "$R/effects" \
    -o "$WORK/rd_stress2" \
    "$HERE/rd_stress2.cpp" \
    "$R/src/RD_Synth_Bridge_v2.cpp" \
    "$R/src/rd_effects.cpp" \
    "$R/src/rd_engine/rd_new_engine.cpp" \
    "$WORK/rd_packs_tables.cpp" \
    "$WORK/rd_packs_blob.S" \
    "$WORK/rd_rom_blob.S" \
    "$WORK/rd_rom_tables.S"

# 3) The packs are input now: they live beside the ROMs and both the firmware
# build and this harness read the same files. Nothing to dump.

# 4) A/B matrix vs the reference emulator
# Cases: patch:note:expected_r (vel always 110)
#
# Re-run 2026-08-26 against giulioz/rdpiano in its original state, after the
# reference was switched away from an adapted copy of it (see the header).
# Every one of the six values frozen on 2026-08-25 came back IDENTICAL to six
# decimals -- so those numbers were never measuring the adaptation, and the
# switch confirms them rather than moving them. What it removes is the risk
# that a later run picks up a checkout somebody has since modified.
#
# Six cells added at the same time, to cover more than middle C on four patches:
#
#   2:72    a second MKS-20 piano, an octave up
#   6:48    E-Piano 1 low
#   10:84   MK-80 Blend high
#   12:60   MK-80 A. Piano 1, the one patch whose held-phase minimum is highest
#   14:55   MK-80 Clavi, 32 kHz
#   3:96    the hard one, and deliberately so. Harpsichord in the top octave is
#           where waveform correlation falls apart -- 0.9868 here, and lower
#           still further up. It is not a timbre difference: pitch matches to
#           0.0 cents, level to 0.4 %, and the third-octave spectrum to 0.11 dB.
#           What differs is the phase of the partials, which at ~12 samples per
#           period is what rounding in a phase accumulator does. The cell earns
#           its place by being sensitive: anything that really changes the top
#           octave will move it well beyond the 0.002 band.
ab_cases="0:60:0.999640 0:36:0.998891 2:72:0.994845 3:60:0.991473 3:96:0.986809
          4:60:0.998967 6:48:0.999917 8:60:0.998612 10:84:0.999917 12:60:0.999669
          14:55:0.998802 15:60:0.999899"

for c in $ab_cases; do
    patch="${c%%:*}"
    rest="${c#*:}"
    note="${rest%%:*}"
    exp="${rest#*:}"

    total=$((total+1))
    out="$("$WORK/rd_ab_test" "$ROMS" "$ROMS" "$patch" "$note" 110 "$WORK/ab_p${patch}n${note}" 2>/dev/null)"
    last="$(printf '%s\n' "$out" | tail -n 1)"
    r="$(printf '%s' "$last" | sed -n 's/.* r=\([0-9.]*\).*/\1/p')"
    rmsRatio="$(printf '%s' "$last" | sed -n 's/.* rmsRatio=\([0-9.]*\).*/\1/p')"

    # |r - exp| <= 0.002
    abs_diff=""
    if [ -n "$r" ]; then
        abs_diff="$(awk -v a="$r" -v b="$exp" 'BEGIN{ d=a-b; if(d<0) d=-d; printf("%.6f", d) }')"
    fi
    r_ok="no"
    if flt "$abs_diff" "<=" "0.002"; then
        r_ok="yes"
    fi

    # 0.85 <= rmsRatio <= 1.15
    rms_ok="no"
    if flt "$rmsRatio" ">=" "0.85" && flt "$rmsRatio" "<=" "1.15"; then
        rms_ok="yes"
    fi

    if [ "$r_ok" = "yes" ] && [ "$rms_ok" = "yes" ]; then
        printf '[ok]   A/B p%-2s n%-3s r=%s (exp %s)  rmsRatio=%s\n' \
            "$patch" "$note" "$r" "$exp" "$rmsRatio"
    else
        fails=$((fails+1))
        printf '[FAIL] A/B p%-2s n%-3s r=%s (exp %s)  rmsRatio=%s\n' \
            "$patch" "$note" "${r:-<no output>}" "$exp" "${rmsRatio:-<no output>}"
    fi
done

# 5) Stress tests (stuck-voice detector)
# Cases: "instr usePedal dual"; PASS iff tailRMS < 0.001
while IFS= read -r line; do
    [ -z "$line" ] && continue
    set -- $line
    instr="$1"; pedal="$2"; dual="$3"

    total=$((total+1))
    out="$("$WORK/rd_stress2" "$instr" "$pedal" "$dual" 2>/dev/null)"
    last="$(printf '%s\n' "$out" | tail -n 1)"
    tailRMS="$(printf '%s' "$last" | sed -n 's/.* tailRMS=\([0-9.]*\).*/\1/p')"

    if flt "$tailRMS" "<" "0.001"; then
        printf '[ok]   stress instr=%s pedal=%s dual=%s tailRMS=%s\n' \
            "$instr" "$pedal" "$dual" "$tailRMS"
    else
        fails=$((fails+1))
        printf '[FAIL] stress instr=%s pedal=%s dual=%s tailRMS=%s\n' \
            "$instr" "$pedal" "$dual" "${tailRMS:-<no output>}"
    fi
done <<EOF_STRESS
4 1 0
4 1 1
0 1 1
EOF_STRESS

# 6) Summary
if [ "$fails" -eq 0 ]; then
    echo "REGRESSION PASS ($total checks)"
    exit 0
else
    echo "REGRESSION FAIL ($fails/$total checks failed)"
    exit 1
fi
