#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Michi71
# run_regression.sh
# One-command host regression runner for PicoFaceRD.
# Builds three host tools, dumps the 16 embedded .rdp packs, runs an A/B
# matrix against the reference emulator, runs stuck-voice stress tests, and
# aggregates a final PASS/FAIL summary.
#
# Usage: ./run_regression.sh
# Generated by glm-5.2:cloud, formally reviewed by the orchestrator.
# Orchestrator fixes: stress FAIL now increments the fail counter, empty
# parse results (tool crash) count as FAIL, dead placeholder loop removed.

set -u

# Two roots, because the move into the collection split what used to be one
# tree: the engine went to instruments/PicoFaceRD/ ($R, still addressed as
# "$R/include" and "$R/src" throughout), while these harnesses went to
# tools/rd_extract/ at the repository root ($HERE). The first version of this
# line kept only $R and left the harness sources under "$R/tools/rd_extract",
# where nothing has been since the merge - so the runner failed on its very
# first build and stayed that way.
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
R="$REPO/instruments/PicoFaceRD"
WORK="$REPO/build_host"
mkdir -p "$WORK/packs"

fails=0
total=0

# float compare: arg1=lhs arg2=op arg3=rhs. Returns 0 if expr true.
# Empty lhs (failed parse) is never true -> caller treats it as FAIL.
flt() {
    local lhs="$1"; local op="$2"; local rhs="$3"
    [ -n "$lhs" ] || return 1
    awk -v a="$lhs" -v b="$rhs" -v o="$op" 'BEGIN{
        r=0
        if(o=="<="){ r=(a<=b) }
        else if(o==">="){ r=(a>=b) }
        else if(o=="=="){ r=(a==b) }
        else if(o=="<"){ r=(a<b) }
        else if(o==">"){ r=(a>b) }
        else if(o=="!="){ r=(a!=b) }
        exit(r?0:1)
    }'
}

# Build helper: echoes a [build] line, runs clang++, checks status.
build_tool() {
    local tool="$1"; shift
    echo "[build] $tool"
    if ! "$@"; then
        echo "[FAIL] build $tool"
        exit 1
    fi
}

# 2) Build tools
build_tool rd_dump_packs \
    clang++ -O2 -std=c++17 -I "$R/include" -I "$R/include/rd_engine" \
    -o "$WORK/rd_dump_packs" \
    "$HERE/rd_dump_packs.cpp" \
    "$R/src/rd_engine/rd_packs_data.cpp"

build_tool rd_ab_test \
    clang++ -O2 -std=c++17 -I "$R/include" -I "$R/include/rd_engine" \
    -o "$WORK/rd_ab_test" \
    "$HERE/rd_ab_test.cpp" \
    "$R/src/rd_engine/mcu.cpp" \
    "$R/src/rd_engine/sound_chip.cpp" \
    "$R/src/rd_engine/mks20a_tables.cpp" \
    "$R/src/rd_engine/mks20b_tables.cpp" \
    "$R/src/rd_engine/mk80_tables.cpp" \
    "$R/src/rd_engine/program_tables.cpp" \
    "$R/src/rd_engine/rd_samples_ilv_a.cpp" \
    "$R/src/rd_engine/rd_samples_ilv_b.cpp" \
    "$R/src/rd_engine/rd_samples_ilv_m.cpp" \
    "$R/src/rd_engine/rd_new_engine.cpp" \
    "$R/src/rd_engine/rd_samples_pk4_a.cpp" \
    "$R/src/rd_engine/rd_samples_pk4_b.cpp" \
    "$R/src/rd_engine/rd_samples_pk4_m.cpp"

build_tool rd_stress2 \
    clang++ -O2 -std=c++17 -I "$R/include" -I "$R/include/rd_engine" -I "$R/effects" \
    -o "$WORK/rd_stress2" \
    "$HERE/rd_stress2.cpp" \
    "$R/src/RD_Synth_Bridge_v2.cpp" \
    "$R/src/rd_effects.cpp" \
    "$R/src/rd_engine/rd_new_engine.cpp" \
    "$R/src/rd_engine/rd_packs_data.cpp" \
    "$R/src/rd_engine/program_tables.cpp" \
    "$R/src/rd_engine/rd_samples_pk4_a.cpp" \
    "$R/src/rd_engine/rd_samples_pk4_b.cpp" \
    "$R/src/rd_engine/rd_samples_pk4_m.cpp"

# 3) Dump packs
if ! "$WORK/rd_dump_packs" "$WORK/packs"; then
    echo "[FAIL] dump packs"
    exit 1
fi

# 4) A/B matrix vs reference emulator
# Cases: patch:note:expected_r (vel always 110)
# Values re-frozen 2026-07-20 after the P4a analyzer fix (pre-attack env
# pulse no longer dropped): matrix median 0.9725 -> 0.9997.
ab_cases="0:60:0.999640 0:36:0.963959 3:60:0.993413 4:60:0.998520 8:60:0.999158 15:60:0.999897"

for c in $ab_cases; do
    patch="${c%%:*}"
    rest="${c#*:}"
    note="${rest%%:*}"
    exp="${rest#*:}"

    total=$((total+1))
    out="$("$WORK/rd_ab_test" "$WORK/packs/pack_p${patch}.rdp" "$patch" "$note" 110 "$WORK/ab_p${patch}n${note}" 2>/dev/null)"
    last="$(printf '%s\n' "$out" | tail -n 1)"
    r="$(printf '%s' "$last" | sed -n 's/.* r=\([0-9.]*\).*/\1/p')"
    rmsRatio="$(printf '%s' "$last" | sed -n 's/.* rmsRatio=\([0-9.]*\).*/\1/p')"

    # |r - exp| <= 0.002
    abs_diff=""
    if [ -n "$r" ]; then
        abs_diff="$(awk -v a="$r" -v b="$exp" 'BEGIN{ d=a-b; if(d<0) d=-d; printf("%.6f", d) }')"
    fi
    r_ok="no"
    if flt "$abs_diff" "<=" "0.002"; then
        r_ok="yes"
    fi

    # 0.85 <= rmsRatio <= 1.15
    rms_ok="no"
    if flt "$rmsRatio" ">=" "0.85" && flt "$rmsRatio" "<=" "1.15"; then
        rms_ok="yes"
    fi

    if [ "$r_ok" = "yes" ] && [ "$rms_ok" = "yes" ]; then
        printf '[ok]   A/B p%-2s n%-3s r=%s (exp %s)  rmsRatio=%s\n' \
            "$patch" "$note" "$r" "$exp" "$rmsRatio"
    else
        fails=$((fails+1))
        printf '[FAIL] A/B p%-2s n%-3s r=%s (exp %s)  rmsRatio=%s\n' \
            "$patch" "$note" "${r:-<no output>}" "$exp" "${rmsRatio:-<no output>}"
    fi
done

# 5) Stress tests (stuck-voice detector)
# Cases: "instr usePedal dual"; PASS iff tailRMS < 0.001
while IFS= read -r line; do
    [ -z "$line" ] && continue
    set -- $line
    instr="$1"; pedal="$2"; dual="$3"

    total=$((total+1))
    out="$("$WORK/rd_stress2" "$instr" "$pedal" "$dual" 2>/dev/null)"
    last="$(printf '%s\n' "$out" | tail -n 1)"
    tailRMS="$(printf '%s' "$last" | sed -n 's/.* tailRMS=\([0-9.]*\).*/\1/p')"

    if flt "$tailRMS" "<" "0.001"; then
        printf '[ok]   stress instr=%s pedal=%s dual=%s tailRMS=%s\n' \
            "$instr" "$pedal" "$dual" "$tailRMS"
    else
        fails=$((fails+1))
        printf '[FAIL] stress instr=%s pedal=%s dual=%s tailRMS=%s\n' \
            "$instr" "$pedal" "$dual" "${tailRMS:-<no output>}"
    fi
done <<EOF_STRESS
4 1 0
4 1 1
0 1 1
EOF_STRESS

# 6) Summary
if [ "$fails" -eq 0 ]; then
    echo "REGRESSION PASS ($total checks)"
    exit 0
else
    echo "REGRESSION FAIL ($fails/$total checks failed)"
    exit 1
fi
