#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Michi71
# run_regression.sh
# One-command host regression runner for PicoFaceRD.
# Builds two host tools, runs an A/B matrix against the reference emulator,
# runs stuck-voice stress tests, and aggregates a final PASS/FAIL summary.
#
# Usage: RDPIANO=/path/to/librdpiano ./run_regression.sh
#
# Two things it needs that are deliberately not in this repository:
#
#   RDPIANO       the upstream emulator, whose SoundChip takes three ROM images
#                 -- https://github.com/Michi71/rdpiano. The descrambling lives
#                 there, so this is what builds the sample banks.
#   RDPIANO_REF   the adapted emulator with the model tables compiled in --
#                 https://github.com/Michi71/librdpiano. This is what the A/B
#                 test compares the engine against. Defaults to RDPIANO if that
#                 checkout happens to carry the tables too.
#   roms/     instruments/PicoFaceRD/roms/, holding the nine sample ROMs and
#             the sixteen .rdp packs. Same directory the firmware builds from.
#
# The packs used to be dumped back out of a generated source file in the
# instrument tree. They are input now, not output, so that step is gone.
# Generated by glm-5.2:cloud, formally reviewed by the orchestrator.
# Orchestrator fixes: stress FAIL now increments the fail counter, empty
# parse results (tool crash) count as FAIL, dead placeholder loop removed.

set -u

# Two roots, because the move into the collection split what used to be one
# tree: the engine went to instruments/PicoFaceRD/ ($R, still addressed as
# "$R/include" and "$R/src" throughout), while these harnesses went to
# tools/rd_extract/ at the repository root ($HERE). The first version of this
# line kept only $R and left the harness sources under "$R/tools/rd_extract",
# where nothing has been since the merge - so the runner failed on its very
# first build and stayed that way.
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
R="$REPO/instruments/PicoFaceRD"
WORK="$REPO/build_host"
ROMS="$R/roms"
mkdir -p "$WORK"

if [ -z "${RDPIANO:-}" ]; then
    echo "run_regression: set RDPIANO to a checkout of the upstream emulator" >&2
    echo "    git clone https://github.com/Michi71/rdpiano" >&2
    exit 1
fi
REF="${RDPIANO_REF:-$RDPIANO}"
RD=""
for cand in "$REF/rdpiano" "$REF/librdpiano" "$REF"; do
    if [ -f "$cand/src/mcu.cpp" ] && [ -f "$cand/include/mcu.h" ]; then RD="$cand"; break; fi
done
if [ -z "$RD" ]; then
    echo "run_regression: no src/mcu.cpp under $REF" >&2
    exit 1
fi
if [ ! -f "$RD/src/mks20a_tables.cpp" ]; then
    echo "run_regression: $RD has no model tables, so the A/B test has nothing" >&2
    echo "    to compare against. Set RDPIANO_REF to a checkout that has them:" >&2
    echo "    git clone https://github.com/Michi71/librdpiano" >&2
    exit 1
fi
if [ ! -f "$ROMS/pack_p0.rdp" ]; then
    echo "run_regression: no ROM set in $ROMS; see instruments/PicoFaceRD/README.md" >&2
    exit 1
fi

# The sample banks the engine reads, built from the ROMs exactly as the
# firmware build does it. Only the banks -- the emulator computes the two
# lookup tables itself, and linking both would define them twice.
echo "[prep] sample banks"
RDPIANO="$RDPIANO" "$HERE/rd_make_rom.sh" "$ROMS" "$WORK/rd_rom.blob" >/dev/null || {
    echo "[FAIL] rd_make_rom"; exit 1; }
echo "[prep] descriptor packs"
python3 "$HERE/rd_embed_packs.py" "$ROMS" "$WORK" >/dev/null || {
    echo "[FAIL] rd_embed_packs"; exit 1; }

fails=0
total=0

# float compare: arg1=lhs arg2=op arg3=rhs. Returns 0 if expr true.
# Empty lhs (failed parse) is never true -> caller treats it as FAIL.
flt() {
    local lhs="$1"; local op="$2"; local rhs="$3"
    [ -n "$lhs" ] || return 1
    awk -v a="$lhs" -v b="$rhs" -v o="$op" 'BEGIN{
        r=0
        if(o=="<="){ r=(a<=b) }
        else if(o==">="){ r=(a>=b) }
        else if(o=="=="){ r=(a==b) }
        else if(o=="<"){ r=(a<b) }
        else if(o==">"){ r=(a>b) }
        else if(o=="!="){ r=(a!=b) }
        exit(r?0:1)
    }'
}

# Build helper: echoes a [build] line, runs clang++, checks status.
build_tool() {
    local tool="$1"; shift
    echo "[build] $tool"
    if ! "$@"; then
        echo "[FAIL] build $tool"
        exit 1
    fi
}

# 2) Build tools
# Both trees carry a rom_tables.h and they declare different things: the
# emulator's names its decoded arrays, the engine's names the packed banks. The
# A/B test includes headers from both, so it gets a third that is the union,
# ahead of either on the include path.
mkdir -p "$WORK/shim"
cp "$RD/include/rom_tables.h" "$WORK/shim/ref_rom_tables.h"
cat > "$WORK/shim/rom_tables.h" <<'SHIM'
/* Generated by run_regression.sh -- the union of the two rom_tables.h, for the
   one translation unit that includes headers from both trees. */
#pragma once
#include <cstdint>
#include "ref_rom_tables.h"
extern const uint32_t rd_samples_pk4_a[0x20000];
extern const uint32_t rd_samples_pk4_b[0x20000];
extern const uint32_t rd_samples_pk4_m[0x20000];
SHIM

# The emulator and its model tables come from the checkout; the sample banks
# from the blob just built. rd_rom_tables.S is left out on purpose here -- the
# emulator's program_tables.cpp already defines those two.
build_tool rd_ab_test \
    clang++ -O2 -w -std=c++17 -I "$WORK/shim" -I "$RD/include" \
        -I "$R/include" -I "$R/include/rd_engine" \
    -o "$WORK/rd_ab_test" \
    "$HERE/rd_ab_test.cpp" \
    "$RD/src/mcu.cpp" \
    "$RD/src/sound_chip.cpp" \
    "$RD/src/mks20a_tables.cpp" \
    "$RD/src/mks20b_tables.cpp" \
    "$RD/src/mk80_tables.cpp" \
    "$RD/src/program_tables.cpp" \
    "$R/src/rd_engine/rd_new_engine.cpp" \
    "$WORK/rd_rom_blob.S"

build_tool rd_stress2 \
    clang++ -O2 -w -std=c++17 -I "$R/include" -I "$R/include/rd_engine" -I "$R/effects" \
    -o "$WORK/rd_stress2" \
    "$HERE/rd_stress2.cpp" \
    "$R/src/RD_Synth_Bridge_v2.cpp" \
    "$R/src/rd_effects.cpp" \
    "$R/src/rd_engine/rd_new_engine.cpp" \
    "$WORK/rd_packs_tables.cpp" \
    "$WORK/rd_packs_blob.S" \
    "$WORK/rd_rom_blob.S" \
    "$WORK/rd_rom_tables.S"

# 3) The packs are input now: they live beside the ROMs and both the firmware
# build and this harness read the same files. Nothing to dump.

# 4) A/B matrix vs reference emulator
# Cases: patch:note:expected_r (vel always 110)
# Values re-frozen 2026-07-20 after the P4a analyzer fix (pre-attack env
# pulse no longer dropped): matrix median 0.9725 -> 0.9997.
ab_cases="0:60:0.999640 0:36:0.963959 3:60:0.993413 4:60:0.998520 8:60:0.999158 15:60:0.999897"

for c in $ab_cases; do
    patch="${c%%:*}"
    rest="${c#*:}"
    note="${rest%%:*}"
    exp="${rest#*:}"

    total=$((total+1))
    out="$("$WORK/rd_ab_test" "$ROMS/pack_p${patch}.rdp" "$patch" "$note" 110 "$WORK/ab_p${patch}n${note}" 2>/dev/null)"
    last="$(printf '%s\n' "$out" | tail -n 1)"
    r="$(printf '%s' "$last" | sed -n 's/.* r=\([0-9.]*\).*/\1/p')"
    rmsRatio="$(printf '%s' "$last" | sed -n 's/.* rmsRatio=\([0-9.]*\).*/\1/p')"

    # |r - exp| <= 0.002
    abs_diff=""
    if [ -n "$r" ]; then
        abs_diff="$(awk -v a="$r" -v b="$exp" 'BEGIN{ d=a-b; if(d<0) d=-d; printf("%.6f", d) }')"
    fi
    r_ok="no"
    if flt "$abs_diff" "<=" "0.002"; then
        r_ok="yes"
    fi

    # 0.85 <= rmsRatio <= 1.15
    rms_ok="no"
    if flt "$rmsRatio" ">=" "0.85" && flt "$rmsRatio" "<=" "1.15"; then
        rms_ok="yes"
    fi

    if [ "$r_ok" = "yes" ] && [ "$rms_ok" = "yes" ]; then
        printf '[ok]   A/B p%-2s n%-3s r=%s (exp %s)  rmsRatio=%s\n' \
            "$patch" "$note" "$r" "$exp" "$rmsRatio"
    else
        fails=$((fails+1))
        printf '[FAIL] A/B p%-2s n%-3s r=%s (exp %s)  rmsRatio=%s\n' \
            "$patch" "$note" "${r:-<no output>}" "$exp" "${rmsRatio:-<no output>}"
    fi
done

# 5) Stress tests (stuck-voice detector)
# Cases: "instr usePedal dual"; PASS iff tailRMS < 0.001
while IFS= read -r line; do
    [ -z "$line" ] && continue
    set -- $line
    instr="$1"; pedal="$2"; dual="$3"

    total=$((total+1))
    out="$("$WORK/rd_stress2" "$instr" "$pedal" "$dual" 2>/dev/null)"
    last="$(printf '%s\n' "$out" | tail -n 1)"
    tailRMS="$(printf '%s' "$last" | sed -n 's/.* tailRMS=\([0-9.]*\).*/\1/p')"

    if flt "$tailRMS" "<" "0.001"; then
        printf '[ok]   stress instr=%s pedal=%s dual=%s tailRMS=%s\n' \
            "$instr" "$pedal" "$dual" "$tailRMS"
    else
        fails=$((fails+1))
        printf '[FAIL] stress instr=%s pedal=%s dual=%s tailRMS=%s\n' \
            "$instr" "$pedal" "$dual" "${tailRMS:-<no output>}"
    fi
done <<EOF_STRESS
4 1 0
4 1 1
0 1 1
EOF_STRESS

# 6) Summary
if [ "$fails" -eq 0 ]; then
    echo "REGRESSION PASS ($total checks)"
    exit 0
else
    echo "REGRESSION FAIL ($fails/$total checks failed)"
    exit 1
fi
