// src/midi_reface.cpp
//
// PicoFaceCP — Yamaha reface CP compatible MIDI layer, implementation.
// Generated by glm-5.2:cloud (orchestrated), assembled from reviewed parts.

#include "midi_reface.h"
#include "ipc.h"
#include "mdaEPiano.h"
#include "reface_cp_chain.h"
#include "presets.h"
#include "pico/stdlib.h"
#include "tusb.h"
#include <string.h>

extern "C" int ui_get_octave(void);

static inline uint32_t nowMs() {
    return to_ms_since_boot(get_absolute_time());
}

void RefaceMidi::init(mdaEPiano* ep, RefaceCpChain* fx) {
    _ep = ep;
    _fx = fx;
    memset(_sys, 0, SYS_BLOCK_SIZE);

    _sys[SYS_TX_CH]        = 0;
    _sys[SYS_RX_CH]        = RX_CH_ALL;
    _sys[SYS_TUNE_HH]      = 0x00;
    _sys[SYS_TUNE_HL]      = 0x04;
    _sys[SYS_TUNE_LH]      = 0x00;
    _sys[SYS_TUNE_LL]      = 0x00;
    _sys[SYS_LOCAL]        = 1;
    _sys[SYS_TRANSPOSE]    = 0x40;
    _sys[SYS_SUSTAIN_SEL]  = 0;
    _sys[SYS_AUTO_POWER_OFF] = 1;
    _sys[SYS_SPEAKER_OUT]  = 1;
    _sys[SYS_MIDI_CONTROL] = 1;

    _softPedal    = false;
    _senseActive  = false;
    _lastRxMs     = nowMs();
    _lastTxSenseMs = nowMs();
}

void RefaceMidi::tick() {
    uint32_t now = nowMs();

    if (now - _lastTxSenseMs >= 200) {
        uint8_t fe = 0xFE;
        txBytes(&fe, 1);
        _lastTxSenseMs = now;
    }

    if (_senseActive && (now - _lastRxMs) > 350) {
        _senseActive = false;
        allSoundOff();
        allNotesOff();
    }
}

void RefaceMidi::notifyActivity() {
    _lastRxMs = nowMs();
}

void RefaceMidi::onRealtime(uint8_t s) {
    if (s == 0xFE) {
        _senseActive = true;
    }
}

bool RefaceMidi::channelOk(uint8_t ch) const {
    uint8_t rx = _sys[SYS_RX_CH];
    return (rx == RX_CH_ALL) || ((ch & 0x0F) == rx);
}

int RefaceMidi::transposeNote(int note) const {
    note += (int)_sys[SYS_TRANSPOSE] - 0x40 + 12 * ui_get_octave();
    if (note < 0)   note = 0;
    if (note > 127) note = 127;
    return note;
}

void RefaceMidi::onNoteOn(uint8_t note, uint8_t vel, uint8_t ch) {
    if (!channelOk(ch)) return;
    if (vel == 0) {
        ipc_send_note_off((uint8_t)transposeNote(note));
        return;
    }
    uint8_t v = vel;
    if (_softPedal) {
        v = (uint8_t)((v * 3) / 4);
        if (v < 1) v = 1;
    }
    ipc_send_note_on((uint8_t)transposeNote(note), v);
}

void RefaceMidi::onNoteOff(uint8_t note, uint8_t vel, uint8_t ch) {
    (void)vel;
    if (!channelOk(ch)) return;
    ipc_send_note_off((uint8_t)transposeNote(note));
}

void RefaceMidi::onPitchBend(uint16_t bend14, uint8_t ch) {
    if (!channelOk(ch)) return;
    ipc_send_pitch_bend(bend14);
}

void RefaceMidi::allSoundOff() {
    ipc_send_cc(0x78, 0);
}

void RefaceMidi::allNotesOff() {
    ipc_send_cc(0x7B, 0);
}

void RefaceMidi::resetControllers() {
    ipc_send_pitch_bend(8192);
    ipc_send_fx_param(FX_EXPRESSION, 1.0f);
    _softPedal = false;
    ipc_send_cc(0x40, 0);
    ipc_send_cc(0x42, 0);
    ipc_send_cc(0x79, 0);
}

void RefaceMidi::setRxChannel(uint8_t ch) {
    if (ch > RX_CH_ALL) ch = RX_CH_ALL;
    _sys[SYS_RX_CH] = ch;
}

uint8_t RefaceMidi::ccZone3(uint8_t v) {
    return (v <= 42) ? 0 : (v <= 85) ? 1 : 2;
}

void RefaceMidi::txBytes(const uint8_t* b, uint16_t n) {
    if (tud_midi_mounted()) {
        tud_midi_stream_write(0, b, n);
    }
}

void RefaceMidi::txCC(uint8_t cc, uint8_t val) {
    uint8_t m[3] = {
        (uint8_t)(0xB0 | (_sys[SYS_TX_CH] & 0x0F)),
        (uint8_t)(cc & 0x7F),
        (uint8_t)(val & 0x7F)
    };
    txBytes(m, 3);
}

void RefaceMidi::txFxParam(uint8_t fxParam, float v01) {
    if (!midiControlEnabled()) return;

    uint8_t cc;
    switch ((FxParam)fxParam) {
        case FX_DRIVE:      cc = 81; break;
        case FX_TW_DEPTH:   cc = 18; break;
        case FX_TW_RATE:    cc = 19; break;
        case FX_CP_DEPTH:   cc = 86; break;
        case FX_CP_SPEED:   cc = 87; break;
        case FX_DLY_DEPTH:  cc = 89; break;
        case FX_DLY_TIME:   cc = 90; break;
        case FX_REVERB:     cc = 91; break;
        default: return;
    }

    if (v01 < 0.0f) v01 = 0.0f;
    if (v01 > 1.0f) v01 = 1.0f;
    txCC(cc, (uint8_t)(v01 * 127.0f + 0.5f));
}

void RefaceMidi::txFxMode(uint8_t fxMode, int mode) {
    if (!midiControlEnabled()) return;

    uint8_t cc;
    switch ((FxMode)fxMode) {
        case FXM_TW_MODE:  cc = 17; break;
        case FXM_CP_MODE:  cc = 85; break;
        case FXM_DLY_MODE: cc = 88; break;
        default: return;
    }

    uint8_t val;
    if (mode == 0)      val = 0;
    else if (mode == 1) val = 64;
    else                val = 127;

    txCC(cc, val);
}

void RefaceMidi::txInstrument(int instr) {
    if (!midiControlEnabled()) return;
    static const uint8_t t[6] = {0, 25, 51, 76, 102, 127};
    if (instr < 0) instr = 0;
    if (instr > 5) instr = 5;
    txCC(80, t[instr]);
}

// Program Change is a PicoFaceCP extension (the original has no PC at all),
// so it is not gated by the MIDI Control setting -- like notes.
void RefaceMidi::txProgram(int preset) {
    if (preset < 0) preset = 0;
    if (preset > CP_NPRESETS - 1) preset = CP_NPRESETS - 1;
    uint8_t msg[2];
    msg[0] = 0xC0 | (_sys[SYS_TX_CH] & 0x0F);
    msg[1] = (uint8_t)preset;
    txBytes(msg, 2);
}

void RefaceMidi::onProgramChange(uint8_t program, uint8_t ch) {
    if (!channelOk(ch)) return;
    if (program >= CP_NPRESETS) return;
    preset_set_current(program);
    ipc_send_program(program);
}

// ===========================================================================
// Part 2: Control Change dispatch (reface CP Data List p.11 + p.13)
// ===========================================================================
void RefaceMidi::onControlChange(uint8_t cc, uint8_t val, uint8_t ch) {
    if (!channelOk(ch)) return;

    float v01 = (float)val / 127.0f;

    switch (cc) {
    case 1:  ipc_send_fx_param(FX_TW_DEPTH, v01); break;
    case 7:  ipc_send_fx_param(FX_VOLUME, v01); break;
    case 11: ipc_send_fx_param(FX_EXPRESSION, v01); break;
    case 64: ipc_send_cc(0x40, val); break;
    case 66: ipc_send_cc(0x42, val); break;
    case 67: _softPedal = (val >= 64); break;

    case 17: if (midiControlEnabled()) ipc_send_fx_mode(FXM_TW_MODE, ccZone3(val)); break;
    case 18: if (midiControlEnabled()) ipc_send_fx_param(FX_TW_DEPTH, v01); break;
    case 19: if (midiControlEnabled()) ipc_send_fx_param(FX_TW_RATE, v01); break;
    case 80: {
        if (midiControlEnabled()) {
            uint8_t i;
            if      (val <= 21)  i = 0;
            else if (val <= 42)  i = 1;
            else if (val <= 64)  i = 2;
            else if (val <= 85)  i = 3;
            else if (val <= 106) i = 4;
            else                 i = 5;
            ipc_send_instrument(i);
        }
        break;
    }
    case 81: if (midiControlEnabled()) ipc_send_fx_param(FX_DRIVE, v01); break;
    case 85: if (midiControlEnabled()) ipc_send_fx_mode(FXM_CP_MODE, ccZone3(val)); break;
    case 86: if (midiControlEnabled()) ipc_send_fx_param(FX_CP_DEPTH, v01); break;
    case 87: if (midiControlEnabled()) ipc_send_fx_param(FX_CP_SPEED, v01); break;
    case 88: if (midiControlEnabled()) ipc_send_fx_mode(FXM_DLY_MODE, ccZone3(val)); break;
    case 89: if (midiControlEnabled()) ipc_send_fx_param(FX_DLY_DEPTH, v01); break;
    case 90: if (midiControlEnabled()) ipc_send_fx_param(FX_DLY_TIME, v01); break;
    case 91: if (midiControlEnabled()) ipc_send_fx_param(FX_REVERB, v01); break;

    case 120: allSoundOff(); break;
    case 121: resetControllers(); break;
    case 123: allNotesOff(); break;
    case 124: allNotesOff(); _sys[SYS_RX_CH] = 0; break;
    case 125: allNotesOff(); _sys[SYS_RX_CH] = RX_CH_ALL; break;
    case 126: allSoundOff(); ipc_send_cc(0x7E, val); break;
    case 127: allSoundOff(); ipc_send_cc(0x7F, 0); break;

    default: break;
    }
}

// ===========================================================================
// Part 3a: SysEx RX dispatch (reface CP Data List p.11: 3-4-1 .. 3-4-5)
// ===========================================================================
void RefaceMidi::onSysEx(const uint8_t* d, uint16_t len)
{
    if (len >= 6 && d[0] == 0xF0 && d[1] == 0x7E && d[3] == 0x06 && d[4] == 0x01) {
        txIdentityReply();
        return;
    }
    if (len >= 10 && d[0] == 0xF0 && d[1] == 0x43 && d[3] == 0x7F && d[4] == 0x1C) {
        handleYamahaSysEx(d, len);
    }
}

void RefaceMidi::handleYamahaSysEx(const uint8_t* d, uint16_t len)
{
    uint8_t cmd = d[2] & 0x70;
    switch (cmd) {
    case 0x10: {
        if (len < 11 || d[5] != 0x04) return;
        uint8_t ah = d[6], am = d[7], al = d[8];
        uint16_t dlen = len - 10;
        const uint8_t* data = &d[9];
        if (ah == 0x00 && am == 0x00) {
            applySystemParam(al, data, dlen);
        } else if (ah == 0x30 && am == 0x00 && dlen >= 1) {
            applyTgParam(al, data[0]);
        }
        break;
    }
    case 0x30: {
        if (len < 10 || d[5] != 0x04) return;
        txParamChange(d[6], d[7], d[8]);
        break;
    }
    case 0x20: {
        if (len < 10 || d[5] != 0x04) return;
        handleDumpRequest(d[6], d[7], d[8]);
        break;
    }
    case 0x00: {
        handleBulkDump(d, len);
        break;
    }
    default:
        break;
    }
}

void RefaceMidi::handleBulkDump(const uint8_t* d, uint16_t len)
{
    if (len < 13) return;
    uint16_t bc = ((uint16_t)(d[5] & 0x7F) << 7) | (d[6] & 0x7F);
    if (bc < 4 || len != (uint16_t)(bc + 9)) return;
    if (d[7] != 0x04) return;
    uint32_t sum = 0;
    for (uint16_t i = 7; i < (uint16_t)(len - 1); i++) sum += d[i];
    if (sum & 0x7F) return;
    uint8_t ah = d[8], am = d[9], al = d[10];
    uint16_t dlen = bc - 4;
    const uint8_t* data = &d[11];
    if (ah == 0x00 && am == 0x00 && al == 0x00 && dlen == SYS_BLOCK_SIZE) {
        for (uint16_t i = 0; i < dlen; i++) {
            applySystemParam((uint8_t)i, &data[i], 1);
        }
    } else if (ah == 0x30 && am == 0x00 && al == 0x00 && dlen == TG_BLOCK_SIZE) {
        for (uint16_t i = 0; i < dlen; i++) {
            applyTgParam((uint8_t)i, data[i]);
        }
    } else {
        // bulk header (0x0E,0x0F,0x00) / footer (0x0F,0x0F,0x00) with dlen==0: ignore
    }
}

void RefaceMidi::handleDumpRequest(uint8_t ah, uint8_t am, uint8_t al)
{
    if (ah == 0x00 && am == 0x00 && al == 0x00) {
        txBulkBlock(0x00, 0x00, 0x00, _sys, SYS_BLOCK_SIZE);
    } else if (ah == 0x0E && am == 0x0F && al == 0x00) {
        txBulkBlock(0x0E, 0x0F, 0x00, nullptr, 0);
        uint8_t tg[TG_BLOCK_SIZE];
        for (uint8_t i = 0; i < TG_BLOCK_SIZE; i++) tg[i] = readTgParam(i);
        txBulkBlock(0x30, 0x00, 0x00, tg, TG_BLOCK_SIZE);
        txBulkBlock(0x0F, 0x0F, 0x00, nullptr, 0);
    } else if (ah == 0x30 && am == 0x00 && al == 0x00) {
        uint8_t tg[TG_BLOCK_SIZE];
        for (uint8_t i = 0; i < TG_BLOCK_SIZE; i++) tg[i] = readTgParam(i);
        txBulkBlock(0x30, 0x00, 0x00, tg, TG_BLOCK_SIZE);
    } else {
        // ignore
    }
}

// ===========================================================================
// Part 3b: parameter apply (SYSTEM / TG blocks, reface CP Data List p.13)
// ===========================================================================
void RefaceMidi::applySystemParam(uint8_t addr, const uint8_t* data, uint16_t len) {
    if (len < 1 || addr >= SYS_BLOCK_SIZE) return;
    uint8_t v = data[0] & 0x7F;
    switch (addr) {
        case SYS_TX_CH:
            if (v <= 0x0F) _sys[addr] = v;
            break;
        case SYS_RX_CH:
            if (v <= RX_CH_ALL) _sys[addr] = v;
            break;
        case SYS_TUNE_HH:
            if (len >= 4) {
                _sys[SYS_TUNE_HH] = data[0] & 0x0F;
                _sys[SYS_TUNE_HL] = data[1] & 0x0F;
                _sys[SYS_TUNE_LH] = data[2] & 0x0F;
                _sys[SYS_TUNE_LL] = data[3] & 0x0F;
            } else {
                _sys[addr] = v & 0x0F;
            }
            applyMasterTune();
            break;
        case SYS_TUNE_HL:
        case SYS_TUNE_LH:
        case SYS_TUNE_LL:
            _sys[addr] = v & 0x0F;
            applyMasterTune();
            break;
        case SYS_LOCAL:
        case SYS_SUSTAIN_SEL:
        case SYS_AUTO_POWER_OFF:
        case SYS_SPEAKER_OUT:
        case SYS_MIDI_CONTROL:
            _sys[addr] = (v != 0) ? 1 : 0;
            break;
        case SYS_TRANSPOSE:
            if (v < 0x34) v = 0x34;
            if (v > 0x4C) v = 0x4C;
            _sys[addr] = v;
            break;
        default:
            _sys[addr] = v;
            break;
    }
}

void RefaceMidi::applyMasterTune() {
    uint16_t t = ((uint16_t)(_sys[SYS_TUNE_HH] & 0x0F) << 12) |
                 ((uint16_t)(_sys[SYS_TUNE_HL] & 0x0F) << 8) |
                 ((uint16_t)(_sys[SYS_TUNE_LH] & 0x0F) << 4) |
                 (uint16_t)(_sys[SYS_TUNE_LL] & 0x0F);
    float cents = ((int)t - 1024) * 0.1f;
    if (cents < -50.0f) cents = -50.0f;
    if (cents > 50.0f) cents = 50.0f;
    ipc_send_voice_param(9, 0.5f + cents * 0.01f);
}

void RefaceMidi::applyTgParam(uint8_t addr, uint8_t value) {
    uint8_t v = value & 0x7F;
    float v01 = (float)v / 127.0f;
    switch (addr) {
        case TG_VOLUME:
            ipc_send_fx_param(FX_VOLUME, v01);
            break;
        case TG_WAVE_TYPE:
            if (v <= 5) ipc_send_instrument(v);
            break;
        case TG_DRIVE:
            ipc_send_fx_param(FX_DRIVE, v01);
            break;
        case TG_FX1_TYPE:
            if (v <= 2) ipc_send_fx_mode(FXM_TW_MODE, v);
            break;
        case TG_FX1_DEPTH:
            ipc_send_fx_param(FX_TW_DEPTH, v01);
            break;
        case TG_FX1_RATE:
            ipc_send_fx_param(FX_TW_RATE, v01);
            break;
        case TG_FX2_TYPE:
            if (v <= 2) ipc_send_fx_mode(FXM_CP_MODE, v);
            break;
        case TG_FX2_DEPTH:
            ipc_send_fx_param(FX_CP_DEPTH, v01);
            break;
        case TG_FX2_SPEED:
            ipc_send_fx_param(FX_CP_SPEED, v01);
            break;
        case TG_FX3_TYPE:
            if (v <= 2) ipc_send_fx_mode(FXM_DLY_MODE, v);
            break;
        case TG_FX3_DEPTH:
            ipc_send_fx_param(FX_DLY_DEPTH, v01);
            break;
        case TG_FX3_TIME:
            ipc_send_fx_param(FX_DLY_TIME, v01);
            break;
        case TG_REVERB_DEPTH:
            ipc_send_fx_param(FX_REVERB, v01);
            break;
        default:
            break;
    }
}

// ===========================================================================
// Part 3c: TG readback + SysEx TX builders (Identity Reply, Parameter Change,
//          Bulk Dump; reface CP Data List p.11)
// ===========================================================================
uint8_t RefaceMidi::readTgParam(uint8_t addr) const
{
    auto to7 = [](float f) -> uint8_t {
        if (f < 0.0f) f = 0.0f;
        if (f > 1.0f) f = 1.0f;
        return (uint8_t)(f * 127.0f + 0.5f);
    };

    switch (addr) {
        case TG_VOLUME:       return to7(_fx->getVolume());
        case TG_WAVE_TYPE:    return (uint8_t)_ep->getCurrentInstrument();
        case TG_DRIVE:        return to7(_fx->getDrive());
        case TG_FX1_TYPE:     return (uint8_t)_fx->getTremWahMode();
        case TG_FX1_DEPTH:    return to7(_fx->getTremWahDepth());
        case TG_FX1_RATE:     return to7(_fx->getTremWahRate());
        case TG_FX2_TYPE:     return (uint8_t)_fx->getChoPhaMode();
        case TG_FX2_DEPTH:    return to7(_fx->getChoPhaDepth());
        case TG_FX2_SPEED:    return to7(_fx->getChoPhaSpeed());
        case TG_FX3_TYPE:     return (uint8_t)_fx->getDelayMode();
        case TG_FX3_DEPTH:    return to7(_fx->getDelayDepth());
        case TG_FX3_TIME:     return to7(_fx->getDelayTime());
        case TG_REVERB_DEPTH: return to7(_fx->getReverbDepth());
        default:              return 0;
    }
}

void RefaceMidi::txIdentityReply()
{
    static const uint8_t r[15] = {
        0xF0, 0x7E, 0x7F, 0x06, 0x02,
        0x43, 0x00, 0x41, 0x52, 0x06,
        0x00, 0x00, 0x00, 0x7F, 0xF7
    };
    txBytes(r, sizeof(r));
}

void RefaceMidi::txParamChange(uint8_t ah, uint8_t am, uint8_t al)
{
    uint8_t buf[16];
    uint16_t n = 0;
    buf[n++] = 0xF0;
    buf[n++] = 0x43;
    buf[n++] = 0x10;
    buf[n++] = 0x7F;
    buf[n++] = 0x1C;
    buf[n++] = 0x04;
    buf[n++] = ah & 0x7F;
    buf[n++] = am & 0x7F;
    buf[n++] = al & 0x7F;

    if (ah == 0x00 && am == 0x00) {
        if (al == SYS_TUNE_HH) {
            buf[n++] = _sys[2];
            buf[n++] = _sys[3];
            buf[n++] = _sys[4];
            buf[n++] = _sys[5];
        } else if (al < SYS_BLOCK_SIZE) {
            buf[n++] = _sys[al];
        } else {
            return;
        }
    } else if (ah == 0x30 && am == 0x00 && al < TG_BLOCK_SIZE) {
        buf[n++] = readTgParam(al);
    } else {
        return;
    }

    buf[n++] = 0xF7;
    txBytes(buf, n);
}

void RefaceMidi::txBulkBlock(uint8_t ah, uint8_t am, uint8_t al, const uint8_t* data, uint8_t len)
{
    uint8_t buf[48];
    uint16_t bc = (uint16_t)4 + len;
    uint16_t n = 0;

    buf[n++] = 0xF0;
    buf[n++] = 0x43;
    buf[n++] = 0x00;
    buf[n++] = 0x7F;
    buf[n++] = 0x1C;
    buf[n++] = (uint8_t)((bc >> 7) & 0x7F);
    buf[n++] = (uint8_t)(bc & 0x7F);
    buf[n++] = 0x04;
    buf[n++] = ah & 0x7F;
    buf[n++] = am & 0x7F;
    buf[n++] = al & 0x7F;

    uint32_t sum = 0x04 + (ah & 0x7F) + (am & 0x7F) + (al & 0x7F);
    for (uint8_t i = 0; i < len; i++) {
        uint8_t b = data[i] & 0x7F;
        buf[n++] = b;
        sum += b;
    }

    buf[n++] = (uint8_t)((0x80 - (sum & 0x7F)) & 0x7F);
    buf[n++] = 0xF7;
    txBytes(buf, n);
}

// Copy the 32-byte SYSTEM common image for persistence.
void RefaceMidi::getSystemBlock(uint8_t* dst) const {
  memcpy(dst, _sys, SYS_BLOCK_SIZE);
}

// Restore the 32-byte SYSTEM common image, sanitize fields, re-apply master tune.
void RefaceMidi::loadSystemBlock(const uint8_t* src) {
  memcpy(_sys, src, SYS_BLOCK_SIZE);
  if (_sys[SYS_RX_CH] > RX_CH_ALL) _sys[SYS_RX_CH] = RX_CH_ALL;
  _sys[SYS_TUNE_HH] &= 0x0F;
  _sys[SYS_TUNE_HL] &= 0x0F;
  _sys[SYS_TUNE_LH] &= 0x0F;
  _sys[SYS_TUNE_LL] &= 0x0F;
  if (_sys[SYS_TRANSPOSE] < 0x34 || _sys[SYS_TRANSPOSE] > 0x4C) _sys[SYS_TRANSPOSE] = 0x40;
  _sys[SYS_LOCAL]        = _sys[SYS_LOCAL]        ? 1 : 0;
  _sys[SYS_MIDI_CONTROL] = _sys[SYS_MIDI_CONTROL] ? 1 : 0;
  applyMasterTune();
}
