// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Michi71

// src/midi_reface.cpp
//
// PicoFaceCP — the reface CP on top of the shared reface MIDI layer.
// CC and TG maps generated by glm-5.2:cloud (orchestrated), assembled from
// reviewed parts.

#include "midi_reface.h"
#include "ipc.h"
#include "mdaEPiano.h"
#include "reface_cp_chain.h"
#include "presets.h"

extern "C" int ui_get_octave(void);

namespace {

const uint8_t kIdentityReply[15] = {
    0xF0, 0x7E, 0x7F, 0x06, 0x02,
    0x43, 0x00, 0x41, 0x52, 0x06,
    0x00, 0x00, 0x00, 0x7F, 0xF7
};

const picoface::RefaceMidiBase::Model kModel = { 0x04, true, kIdentityReply, sizeof kIdentityReply };

} // namespace

RefaceMidi::RefaceMidi() : picoface::RefaceMidiBase(kModel) {}

void RefaceMidi::init(mdaEPiano* ep, RefaceCpChain* fx) {
  _ep = ep;
  _fx = fx;
  resetSystem();
  _sys[SYS_SUSTAIN_SEL] = 0;
  _softPedal = false;
}

int RefaceMidi::uiOctave() const { return ui_get_octave(); }

void RefaceMidi::engineNoteOn(uint8_t note, uint8_t vel) {
  uint8_t v = vel;
  if (_softPedal) {
    v = (uint8_t)((v * 3) / 4);
    if (v < 1) v = 1;
  }
  ipc_send_note_on(note, v);
}

void RefaceMidi::engineNoteOff(uint8_t note)      { ipc_send_note_off(note); }
void RefaceMidi::enginePitchBend(uint16_t bend14) { ipc_send_pitch_bend(bend14); }
void RefaceMidi::engineAllSoundOff()              { ipc_send_cc(0x78, 0); }
void RefaceMidi::engineAllNotesOff()              { ipc_send_cc(0x7B, 0); }

void RefaceMidi::resetControllers() {
  ipc_send_pitch_bend(8192);
  ipc_send_fx_param(FX_EXPRESSION, 1.0f);
  _softPedal = false;
  ipc_send_cc(0x40, 0);
  ipc_send_cc(0x42, 0);
  ipc_send_cc(0x79, 0);
}

// 1024 = centre, 0.1 cent per step, into mdaEPiano's fine tune (param 9,
// 0.5 = centre, 0.01 per cent) clamped to the +-50 cents that knob spans.
void RefaceMidi::engineMasterTune(uint16_t raw) {
  float cents = ((int) raw - 1024) * 0.1f;
  if (cents < -50.0f) cents = -50.0f;
  if (cents > 50.0f) cents = 50.0f;
  ipc_send_voice_param(9, 0.5f + cents * 0.01f);
}

void RefaceMidi::applyModelSystemParam(uint8_t addr, uint8_t v) {
  _sys[addr] = (addr == SYS_SUSTAIN_SEL) ? ((v != 0) ? 1 : 0) : v;
}

uint8_t RefaceMidi::ccZone3(uint8_t v) {
  return (v <= 42) ? 0 : (v <= 85) ? 1 : 2;
}

// ===========================================================================
// Front panel -> CC
// ===========================================================================
void RefaceMidi::txFxParam(uint8_t fxParam, float v01) {
  if (!midiControlEnabled()) return;

  uint8_t cc;
  switch ((FxParam)fxParam) {
    case FX_DRIVE:      cc = 81; break;
    case FX_TW_DEPTH:   cc = 18; break;
    case FX_TW_RATE:    cc = 19; break;
    case FX_CP_DEPTH:   cc = 86; break;
    case FX_CP_SPEED:   cc = 87; break;
    case FX_DLY_DEPTH:  cc = 89; break;
    case FX_DLY_TIME:   cc = 90; break;
    case FX_REVERB:     cc = 91; break;
    default: return;
  }

  if (v01 < 0.0f) v01 = 0.0f;
  if (v01 > 1.0f) v01 = 1.0f;
  txCC(cc, (uint8_t)(v01 * 127.0f + 0.5f));
}

void RefaceMidi::txFxMode(uint8_t fxMode, int mode) {
  if (!midiControlEnabled()) return;

  uint8_t cc;
  switch ((FxMode)fxMode) {
    case FXM_TW_MODE:  cc = 17; break;
    case FXM_CP_MODE:  cc = 85; break;
    case FXM_DLY_MODE: cc = 88; break;
    default: return;
  }

  uint8_t val;
  if (mode == 0)      val = 0;
  else if (mode == 1) val = 64;
  else                val = 127;

  txCC(cc, val);
}

void RefaceMidi::txInstrument(int instr) {
  if (!midiControlEnabled()) return;
  static const uint8_t t[6] = {0, 25, 51, 76, 102, 127};
  if (instr < 0) instr = 0;
  if (instr > 5) instr = 5;
  txCC(80, t[instr]);
}

// Program Change is a PicoFaceCP extension (the original has no PC at all),
// so it is not gated by the MIDI Control setting -- like notes.
void RefaceMidi::txProgram(int preset) {
  if (preset < 0) preset = 0;
  if (preset > CP_NPRESETS - 1) preset = CP_NPRESETS - 1;
  txProgramChange((uint8_t) preset);
}

void RefaceMidi::engineProgramChange(uint8_t program) {
  if (program >= CP_NPRESETS) return;
  preset_set_current(program);
  ipc_send_program(program);
}

// ===========================================================================
// Control Change dispatch (reface CP Data List p.11 + p.13). Omni on/off
// (124/125) never get here, the base handles them.
// ===========================================================================
void RefaceMidi::engineControlChange(uint8_t cc, uint8_t val) {
  float v01 = (float)val / 127.0f;

  switch (cc) {
  case 1:  ipc_send_fx_param(FX_TW_DEPTH, v01); break;
  case 7:  ipc_send_fx_param(FX_VOLUME, v01); break;
  case 11: ipc_send_fx_param(FX_EXPRESSION, v01); break;
  case 64: ipc_send_cc(0x40, val); break;
  case 66: ipc_send_cc(0x42, val); break;
  case 67: _softPedal = (val >= 64); break;

  case 17: if (midiControlEnabled()) ipc_send_fx_mode(FXM_TW_MODE, ccZone3(val)); break;
  case 18: if (midiControlEnabled()) ipc_send_fx_param(FX_TW_DEPTH, v01); break;
  case 19: if (midiControlEnabled()) ipc_send_fx_param(FX_TW_RATE, v01); break;
  case 80: {
    if (midiControlEnabled()) {
      uint8_t i;
      if      (val <= 21)  i = 0;
      else if (val <= 42)  i = 1;
      else if (val <= 64)  i = 2;
      else if (val <= 85)  i = 3;
      else if (val <= 106) i = 4;
      else                 i = 5;
      ipc_send_instrument(i);
    }
    break;
  }
  case 81: if (midiControlEnabled()) ipc_send_fx_param(FX_DRIVE, v01); break;
  case 85: if (midiControlEnabled()) ipc_send_fx_mode(FXM_CP_MODE, ccZone3(val)); break;
  case 86: if (midiControlEnabled()) ipc_send_fx_param(FX_CP_DEPTH, v01); break;
  case 87: if (midiControlEnabled()) ipc_send_fx_param(FX_CP_SPEED, v01); break;
  case 88: if (midiControlEnabled()) ipc_send_fx_mode(FXM_DLY_MODE, ccZone3(val)); break;
  case 89: if (midiControlEnabled()) ipc_send_fx_param(FX_DLY_DEPTH, v01); break;
  case 90: if (midiControlEnabled()) ipc_send_fx_param(FX_DLY_TIME, v01); break;
  case 91: if (midiControlEnabled()) ipc_send_fx_param(FX_REVERB, v01); break;

  case 120: engineAllSoundOff(); break;
  case 121: resetControllers(); break;
  case 123: engineAllNotesOff(); break;
  case 126: engineAllSoundOff(); ipc_send_cc(0x7E, val); break;
  case 127: engineAllSoundOff(); ipc_send_cc(0x7F, 0); break;

  default: break;
  }
}

// ===========================================================================
// TG block (reface CP Data List p.13): apply, read back, dump
// ===========================================================================
void RefaceMidi::applyParam(uint8_t ah, uint8_t am, uint8_t al, const uint8_t* data, uint16_t len) {
  if (ah == 0x30 && am == 0x00 && len >= 1) applyTgParam(al, data[0]);
}

uint8_t RefaceMidi::readParam(uint8_t ah, uint8_t am, uint8_t al, uint8_t* out) {
  if (ah == 0x30 && am == 0x00 && al < TG_BLOCK_SIZE) {
    out[0] = readTgParam(al);
    return 1;
  }
  return 0;
}

void RefaceMidi::onBulkBlock(uint8_t ah, uint8_t am, uint8_t al, const uint8_t* data, uint16_t len) {
  if (ah == 0x30 && am == 0x00 && al == 0x00 && len == TG_BLOCK_SIZE) {
    for (uint16_t i = 0; i < len; i++) applyTgParam((uint8_t) i, data[i]);
  }
  // bulk header (0x0E,0x0F,0x00) / footer (0x0F,0x0F,0x00) with len==0: ignore
}

void RefaceMidi::txTgBlock() {
  uint8_t tg[TG_BLOCK_SIZE];
  for (uint8_t i = 0; i < TG_BLOCK_SIZE; i++) tg[i] = readTgParam(i);
  txBulkBlock(0x30, 0x00, 0x00, tg, TG_BLOCK_SIZE);
}

void RefaceMidi::onDumpRequest(uint8_t ah, uint8_t am, uint8_t al) {
  if (ah == 0x0E && am == 0x0F && al == 0x00) {
    txBulkBlock(0x0E, 0x0F, 0x00, nullptr, 0);
    txTgBlock();
    txBulkBlock(0x0F, 0x0F, 0x00, nullptr, 0);
  } else if (ah == 0x30 && am == 0x00 && al == 0x00) {
    txTgBlock();
  }
}

void RefaceMidi::applyTgParam(uint8_t addr, uint8_t value) {
  uint8_t v = value & 0x7F;
  float v01 = (float)v / 127.0f;
  switch (addr) {
    case TG_VOLUME:
      ipc_send_fx_param(FX_VOLUME, v01);
      break;
    case TG_WAVE_TYPE:
      if (v <= 5) ipc_send_instrument(v);
      break;
    case TG_DRIVE:
      ipc_send_fx_param(FX_DRIVE, v01);
      break;
    case TG_FX1_TYPE:
      if (v <= 2) ipc_send_fx_mode(FXM_TW_MODE, v);
      break;
    case TG_FX1_DEPTH:
      ipc_send_fx_param(FX_TW_DEPTH, v01);
      break;
    case TG_FX1_RATE:
      ipc_send_fx_param(FX_TW_RATE, v01);
      break;
    case TG_FX2_TYPE:
      if (v <= 2) ipc_send_fx_mode(FXM_CP_MODE, v);
      break;
    case TG_FX2_DEPTH:
      ipc_send_fx_param(FX_CP_DEPTH, v01);
      break;
    case TG_FX2_SPEED:
      ipc_send_fx_param(FX_CP_SPEED, v01);
      break;
    case TG_FX3_TYPE:
      if (v <= 2) ipc_send_fx_mode(FXM_DLY_MODE, v);
      break;
    case TG_FX3_DEPTH:
      ipc_send_fx_param(FX_DLY_DEPTH, v01);
      break;
    case TG_FX3_TIME:
      ipc_send_fx_param(FX_DLY_TIME, v01);
      break;
    case TG_REVERB_DEPTH:
      ipc_send_fx_param(FX_REVERB, v01);
      break;
    default:
      break;
  }
}

uint8_t RefaceMidi::readTgParam(uint8_t addr) const
{
  auto to7 = [](float f) -> uint8_t {
    if (f < 0.0f) f = 0.0f;
    if (f > 1.0f) f = 1.0f;
    return (uint8_t)(f * 127.0f + 0.5f);
  };

  switch (addr) {
    case TG_VOLUME:       return to7(_fx->getVolume());
    case TG_WAVE_TYPE:    return (uint8_t)_ep->getCurrentInstrument();
    case TG_DRIVE:        return to7(_fx->getDrive());
    case TG_FX1_TYPE:     return (uint8_t)_fx->getTremWahMode();
    case TG_FX1_DEPTH:    return to7(_fx->getTremWahDepth());
    case TG_FX1_RATE:     return to7(_fx->getTremWahRate());
    case TG_FX2_TYPE:     return (uint8_t)_fx->getChoPhaMode();
    case TG_FX2_DEPTH:    return to7(_fx->getChoPhaDepth());
    case TG_FX2_SPEED:    return to7(_fx->getChoPhaSpeed());
    case TG_FX3_TYPE:     return (uint8_t)_fx->getDelayMode();
    case TG_FX3_DEPTH:    return to7(_fx->getDelayDepth());
    case TG_FX3_TIME:     return to7(_fx->getDelayTime());
    case TG_REVERB_DEPTH: return to7(_fx->getReverbDepth());
    default:              return 0;
  }
}
