#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Michi71
"""midi_keyboard_only.py - strip a Standard MIDI File to pure keyboard performance.

Usage:
    python3 midi_keyboard_only.py input.mid [output.mid]
        [--no-pitch-bend] [--keep-cc N ...] [--quiet]

Zero-dependency (Python 3.8+, stdlib only: sys, argparse, pathlib).

KEEP / DROP table:
  +-----------------------------+--------------------------------+
  | Event                       | Action                         |
  +-----------------------------+--------------------------------+
  | note_on  (0x9n)             | KEEP                           |
  | note_off (0x8n)             | KEEP                           |
  | control_change (0xBn) cc 64 | KEEP                           |
  | control_change (0xBn) cc 123| KEEP                           |
  | control_change (0xBn) --keep-cc | KEEP                       |
  | pitch_bend (0xEn)           | KEEP (unless --no-pitch-bend)  |
  | meta events (0xFF ...)      | KEEP (unchanged)               |
  | control_change (0xBn) other | DROP                           |
  | program_change (0xCn)       | DROP                           |
  | channel_aftertouch (0xDn)   | DROP                           |
  | poly_aftertouch (0xAn)      | DROP                           |
  | sysex (0xF0 / 0xF7)         | DROP                           |
  | unknown status              | ERROR (exit 1)                 |
  +-----------------------------+--------------------------------+

Output rules:
  * MThd copied verbatim.
  * Each MTrk filtered independently (count and order preserved).
  * Delta times of dropped events accumulate onto the next kept event.
  * Kept channel events written with EXPLICIT status (no running status).
  * Meta events written verbatim.
  * MTrk length recomputed.
  * Default output: <stem>_keys.mid.

Generated by glm-5.2:cloud, formally reviewed by the orchestrator.
"""
import sys
import argparse
from pathlib import Path


# ---------------------------------------------------------------------------
# VLQ helpers
# ---------------------------------------------------------------------------
def read_vlq(data: bytes, pos: int):
    """Read a variable-length quantity. Returns (value, new_pos)."""
    value = 0
    for _ in range(4):
        if pos >= len(data):
            raise ValueError("unexpected EOF while reading VLQ")
        b = data[pos]
        pos += 1
        value = (value << 7) | (b & 0x7F)
        if not (b & 0x80):
            return value, pos
    raise ValueError("VLQ too long (>4 bytes)")


def write_vlq(value: int) -> bytes:
    """Write a non-negative integer as a MIDI VLQ."""
    if value < 0:
        raise ValueError("negative VLQ")
    if value == 0:
        return b"\x00"
    out = bytearray()
    out.append(value & 0x7F)
    value >>= 7
    while value:
        out.append((value & 0x7F) | 0x80)
        value >>= 7
    out.reverse()
    return bytes(out)


# ---------------------------------------------------------------------------
# Track-level filtering
# ---------------------------------------------------------------------------
class TrackStats:
    __slots__ = (
        "notes", "sustain", "bend",
        "prog", "cc", "aftertouch", "sysex",
    )

    def __init__(self):
        self.notes = 0      # kept note_on/note_off
        self.sustain = 0    # kept control_change
        self.bend = 0       # kept pitch bend
        self.prog = 0       # dropped program changes
        self.cc = 0         # dropped control changes
        self.aftertouch = 0 # dropped poly/channel aftertouch
        self.sysex = 0      # dropped sysex


# data sizes for channel-voice messages (status nibble high)
DATA_BYTES = {
    0x8: 2,  # note off
    0x9: 2,  # note on
    0xA: 2,  # poly aftertouch
    0xB: 2,  # control change
    0xC: 1,  # program change
    0xD: 1,  # channel aftertouch
    0xE: 2,  # pitch bend
}


def parse_track(track_bytes, keep_cc_set, keep_pitch_bend):
    """Parse a single MTrk body (without the 8-byte chunk header).

    Returns (list_of_output_bytes, stats, name).
    Each output element is a full event (delta_vlq + status + data, or meta).
    """
    out = []
    stats = TrackStats()
    pos = 0
    running_status = None
    name = ""
    ended_eot = False
    pending_delta = 0  # accumulated delta from dropped events

    n = len(track_bytes)
    while pos < n:
        # --- delta time ---
        delta, pos = read_vlq(track_bytes, pos)

        if pos >= n:
            # delta with no event following; track truncated
            sys.stderr.write(
                "warning: track ended after delta with no event\n")
            pending_delta += delta
            break

        b0 = track_bytes[pos]

        # --- running status (data byte where status expected) ---
        if b0 < 0x80:
            if running_status is None:
                raise ValueError(
                    "data byte without preceding channel status at pos %d" % pos)
            status = running_status
            event_delta = delta
            # no status byte to consume
        else:
            status = b0
            pos += 1
            event_delta = delta
            # update running status only for channel-voice messages
            if status < 0xF0:
                running_status = status
            # meta and sysex do NOT update running status

        # --- dispatch ---
        if status == 0xFF:
            # meta event: status already consumed; now type, len, payload
            if pos >= n:
                raise ValueError("truncated meta event")
            meta_type = track_bytes[pos]
            pos += 1
            mlen, pos = read_vlq(track_bytes, pos)
            payload = track_bytes[pos:pos + mlen]
            if len(payload) != mlen:
                raise ValueError("truncated meta payload")
            pos += mlen
            if meta_type == 0x03 and mlen > 0:
                name = payload.decode("ascii", errors="replace")
            # KEEP meta verbatim; include accumulated delta
            buf = bytearray()
            buf += write_vlq(pending_delta + event_delta)
            buf += bytes([0xFF, meta_type])
            buf += write_vlq(mlen)
            buf += payload
            out.append(bytes(buf))
            pending_delta = 0
            if meta_type == 0x2F:
                ended_eot = True
            continue

        if status == 0xF0 or status == 0xF7:
            # sysex event: status consumed; VLQ len, payload
            slen, pos = read_vlq(track_bytes, pos)
            payload = track_bytes[pos:pos + slen]
            if len(payload) != slen:
                raise ValueError("truncated sysex payload")
            pos += slen
            # DROP; accumulate delta
            pending_delta += event_delta
            stats.sysex += 1
            continue

        if 0x80 <= status <= 0xEF:
            high = (status >> 4) & 0x0F
            nbytes = DATA_BYTES[high]
            if pos + nbytes > n:
                raise ValueError("truncated channel event at pos %d" % pos)
            data = track_bytes[pos:pos + nbytes]
            pos += nbytes

            keep = False
            if high in (0x8, 0x9):
                # note off / note on
                keep = True
                stats.notes += 1
            elif high == 0xB:
                cc = data[0]
                if cc == 64 or cc == 123 or cc in keep_cc_set:
                    keep = True
                    stats.sustain += 1
                else:
                    stats.cc += 1
            elif high == 0xE and keep_pitch_bend:
                keep = True
                stats.bend += 1
            elif high == 0xE and not keep_pitch_bend:
                stats.cc += 1  # counted with the dropped controllers
            elif high == 0xA:
                stats.aftertouch += 1
            elif high == 0xC:
                stats.prog += 1
            elif high == 0xD:
                stats.aftertouch += 1

            if keep:
                buf = bytearray()
                buf += write_vlq(pending_delta + event_delta)
                buf += bytes([status])  # explicit status, no running status
                buf += data
                out.append(bytes(buf))
                pending_delta = 0
            else:
                pending_delta += event_delta
            continue

        # unknown status
        raise ValueError("unknown status byte 0x%02X at pos %d" % (status, pos - 1))

    if not ended_eot:
        sys.stderr.write(
            "warning: track did not end with end-of-track meta event\n")

    return out, stats, name


def serialize_track(events):
    """Concatenate event bytes into a single MTrk body."""
    return b"".join(events)


# ---------------------------------------------------------------------------
# File-level
# ---------------------------------------------------------------------------
def parse_header(data: bytes):
    """Parse an MThd chunk from raw bytes. Returns (header_bytes, total_header_len)."""
    if len(data) < 14:
        raise ValueError("file too small for header")
    if data[0:4] != b"MThd":
        raise ValueError("missing MThd")
    hdr_len = int.from_bytes(data[4:8], "big")
    if hdr_len < 6:
        raise ValueError("invalid header length")
    total = 8 + hdr_len
    if len(data) < total:
        raise ValueError("truncated header")
    return data[0:total], total


def build_track_chunk(body: bytes) -> bytes:
    return b"MTrk" + len(body).to_bytes(4, "big") + body


def process_file(input_bytes, keep_cc_set, keep_pitch_bend):
    """Process whole file. Returns (output_bytes, list_of_TrackStats, names)."""
    header, pos = parse_header(input_bytes)
    out_chunks = [header]
    stats_list = []
    names = []

    data = input_bytes
    n = len(data)
    while pos + 8 <= n:
        chunk_id = data[pos:pos + 4]
        chunk_len = int.from_bytes(data[pos + 4:pos + 8], "big")
        body_start = pos + 8
        body_end = body_start + chunk_len
        if body_end > n:
            raise ValueError("truncated chunk '%s'" % chunk_id.decode("ascii",
                                                                     errors="replace"))

        if chunk_id != b"MTrk":
            # copy unknown chunks verbatim
            out_chunks.append(data[pos:body_end])
            pos = body_end
            continue

        track_body = data[body_start:body_end]
        events, stats, name = parse_track(track_body, keep_cc_set,
                                          keep_pitch_bend)
        new_body = serialize_track(events)
        out_chunks.append(build_track_chunk(new_body))
        stats_list.append(stats)
        names.append(name)
        pos = body_end

    if pos != n:
        # trailing garbage; copy verbatim to be safe
        out_chunks.append(data[pos:])

    return b"".join(out_chunks), stats_list, names


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def build_argparser():
    p = argparse.ArgumentParser(
        description="Strip a Standard MIDI File to pure keyboard performance.",
        usage="python3 midi_keyboard_only.py input.mid [output.mid] "
              "[--no-pitch-bend] [--keep-cc N ...] [--quiet]",
    )
    p.add_argument("input", help="input .mid file")
    p.add_argument("output", nargs="?", default=None,
                   help="output .mid file (default: <stem>_keys.mid)")
    p.add_argument("--no-pitch-bend", action="store_true",
                   help="drop pitch bend events")
    p.add_argument("--keep-cc", action="append", type=int, default=None,
                   metavar="N", help="extra CC controller to keep (repeatable)")
    p.add_argument("--quiet", action="store_true",
                   help="suppress summary output")
    return p


def main(argv=None):
    args = build_argparser().parse_args(argv)

    in_path = Path(args.input)
    if not in_path.is_file():
        sys.stderr.write("error: input file not found: %s\n" % in_path)
        return 1

    try:
        in_bytes = in_path.read_bytes()
    except OSError as e:
        sys.stderr.write("error: cannot read input: %s\n" % e)
        return 1

    keep_cc_set = set()
    if args.keep_cc:
        for cc in args.keep_cc:
            if not (0 <= cc <= 127):
                sys.stderr.write("error: --keep-cc value out of range: %d\n" % cc)
                return 1
            keep_cc_set.add(cc)

    try:
        out_bytes, stats_list, names = process_file(
            in_bytes, keep_cc_set, not args.no_pitch_bend)
    except ValueError as e:
        sys.stderr.write("error: %s\n" % e)
        return 1

    if args.output:
        out_path = Path(args.output)
    else:
        out_path = in_path.with_name(in_path.stem + "_keys.mid")

    try:
        out_path.write_bytes(out_bytes)
    except OSError as e:
        sys.stderr.write("error: cannot write output: %s\n" % e)
        return 1

    if not args.quiet:
        for i, (st, name) in enumerate(zip(stats_list, names), start=1):
            disp_name = name if name else "(unnamed)"
            print("track %d %s: kept %d notes, %d sustain, %d bend | "
                  "dropped %d prog, %d cc, %d aftertouch, %d sysex" % (
                      i, disp_name,
                      st.notes, st.sustain, st.bend,
                      st.prog, st.cc, st.aftertouch, st.sysex,
                  ))
        print("%s: %d -> %d bytes" % (out_path, len(in_bytes), len(out_bytes)))

    return 0


if __name__ == "__main__":
    sys.exit(main())
