// cp_audio.h
//
// Glue layer: run the float Reface CP effect chain on int16 PCM blocks.
// The mdaEPiano engine outputs int16 L/R and the I2S buffer expects int16,
// so this converts to float [-1,1], runs RefaceCpChain, and converts back
// with hard clipping. Header-only, no heap.
//
// Generated by glm-5.2:cloud, formally reviewed; assembled by the orchestrator.

#pragma once
#include <cstdint>
#include <cmath>
#include "reface_cp_chain.h"
#include "cp_hot.h"

inline void CP_HOT(cp_process_block_i16)(RefaceCpChain& fx, int16_t* l, int16_t* r, int n) {
    static constexpr int kMaxBlock = 64;
    int offset = 0;
    while (offset < n) {
        int chunk = n - offset;
        if (chunk > kMaxBlock) chunk = kMaxBlock;

        float fl[kMaxBlock];
        float fr[kMaxBlock];

        for (int i = 0; i < chunk; ++i) {
            fl[i] = static_cast<float>(l[offset + i]) / 32768.0f;
            fr[i] = static_cast<float>(r[offset + i]) / 32768.0f;
        }

        fx.process(fl, fr, chunk);

        for (int i = 0; i < chunk; ++i) {
            float v_l = fl[i] * 32768.0f;
            float v_r = fr[i] * 32768.0f;
            if (v_l > 32767.0f) v_l = 32767.0f;
            if (v_l < -32768.0f) v_l = -32768.0f;
            if (v_r > 32767.0f) v_r = 32767.0f;
            if (v_r < -32768.0f) v_r = -32768.0f;
            l[offset + i] = static_cast<int16_t>(lrintf(v_l));
            r[offset + i] = static_cast<int16_t>(lrintf(v_r));
        }

        offset += chunk;
    }
}
