// cp_hot.h
//
// Portability shim: place hot audio functions in RAM on the RP2350 (avoids
// XIP flash-cache jitter inside the I2S IRQ), no-op on the macOS host build.
//
// Usage:  void CP_HOT(process)(float& l, float& r) { ... }
//         inline void CP_HOT(cp_process_block_i16)(...) { ... }
//
// Generated by glm-5.2:cloud, formally reviewed by the orchestrator.

#pragma once

#if defined(__has_include)
#  if __has_include("pico.h")
#    include "pico.h"
#  endif
#endif

#ifdef __not_in_flash_func
#  define CP_HOT(name) __not_in_flash_func(name)
#else
#  define CP_HOT(name) name
#endif
