// reface_cp_fx.h
//
// Self-contained, header-only DSP primitives for the Yamaha Reface CP
// emulation. All effects share the convention:
//     void init(float sr); void reset(); void process(float& l, float& r);
// plus normalized setters (arguments clamped to 0..1).
//
// No heap, single-precision float only -> RP2350 (Cortex-M33 FPU) friendly
// and host-build (macOS Clang, C++17) compatible.
//
// Generated by glm-5.2:cloud, formally reviewed; assembled by the orchestrator.

#pragma once

#include <cmath>
#include <cstdint>
#include "dsp_fastmath.h"   // fastTanh, fastTan
#include "dsp_lut.h"      // g_sinLUT() shared sine LUT
#include "cp_hot.h"         // CP_HOT() RAM placement (Pico) / no-op (host)

static inline float cp_clamp01(float x){ return x < 0.0f ? 0.0f : (x > 1.0f ? 1.0f : x); }

// ============================================================================
// Effect 1a: TREMOLO  (cyclic amplitude modulation)
//   mode 0 = PAN    (auto-pan L/R, for Rd I / Rd II / CP voices)
//   mode 1 = VOLUME (both channels together, for Wr / Clv / Piano voices)
// ============================================================================
struct CpTremolo {
    static constexpr float kTwoPi = 6.28318530718f;

    float sr = 48000.0f;
    float phase = 0.0f;
    float depth = 0.0f;
    float rateHz = 0.1f;
    int mode = 0;

    void init(float sr_) { sr = sr_; reset(); }
    void reset() { phase = 0.0f; }

    void setDepth(float n) { depth = cp_clamp01(n); }
    void setRate(float n)  { n = cp_clamp01(n); rateHz = 0.1f * powf(10.0f, 2.0f * n); } // 0.1..10 Hz
    void setMode(int m)    { mode = (m == 1) ? 1 : 0; }

    void CP_HOT(process)(float& l, float& r) {
        phase += rateHz / sr;
        if (phase >= 1.0f) phase -= 1.0f;
        if (phase < 0.0f)  phase += 1.0f;

        float lfo = g_sinLUT().sin01_nofloor(phase);
        float a = 0.5f + 0.5f * lfo;
        float b = 0.5f - 0.5f * lfo;

        if (mode == 0) { // PAN
            float gL = 1.0f - depth * a;
            float gR = 1.0f - depth * b;
            gL = cp_clamp01(gL);
            gR = cp_clamp01(gR);
            l *= gL;
            r *= gR;
        } else { // VOLUME
            float g = 1.0f - depth * a;
            g = cp_clamp01(g);
            l *= g;
            r *= g;
        }
    }
};

// ============================================================================
// Effect 2a: CHORUS  (stereo modulated delay -> richer / wider)
// ============================================================================
struct CpChorus {
    static constexpr int kBuf = 1024;
    static constexpr float kTwoPi = 6.28318530718f;

    float sr = 48000.0f;
    float phaseL = 0.0f;
    float phaseR = 0.0f;
    float depthMs = 0.0f;
    float rateHz = 0.1f;
    float bufL[kBuf];
    float bufR[kBuf];
    int widx = 0;

    void init(float sr_) { sr = sr_; reset(); }
    void reset() {
        phaseL = 0.0f;
        phaseR = 0.25f; // 90 deg offset
        widx = 0;
        for (int i = 0; i < kBuf; ++i) { bufL[i] = 0.0f; bufR[i] = 0.0f; }
    }

    void setDepth(float n) { depthMs = cp_clamp01(n) * 4.0f; } // 0..4 ms
    void setRate(float n)  { n = cp_clamp01(n); rateHz = 0.1f * powf(10.0f, 1.69897f * n); } // 0.1..5 Hz

    inline float readChan(const float* buf, float delaySamp) {
        float rp = (float)widx - delaySamp;
        while (rp < 0.0f) rp += (float)kBuf;
        int i0 = (int)rp;
        if (i0 >= kBuf) i0 -= kBuf;
        float frac = rp - (float)i0;
        int i1 = i0 + 1;
        if (i1 >= kBuf) i1 = 0;
        return buf[i0] + frac * (buf[i1] - buf[i0]);
    }

    void CP_HOT(process)(float& l, float& r) {
        float inc = rateHz / sr;
        phaseL += inc; if (phaseL >= 1.0f) phaseL -= 1.0f;
        phaseR += inc; if (phaseR >= 1.0f) phaseR -= 1.0f;

        float baseSamp = 0.012f * sr;          // ~12 ms
        float modSamp  = depthMs * 0.001f * sr; // 0..4 ms
        if (baseSamp + modSamp > (float)(kBuf - 2)) modSamp = (float)(kBuf - 2) - baseSamp;

        float dl = baseSamp + modSamp * g_sinLUT().sin01_nofloor(phaseL);
        float dr = baseSamp + modSamp * g_sinLUT().sin01_nofloor(phaseR);

        float dryL = l, dryR = r;
        bufL[widx] = dryL;
        bufR[widx] = dryR;

        float wetL = readChan(bufL, dl);
        float wetR = readChan(bufR, dr);

        l = 0.5f * dryL + 0.5f * wetL;
        r = 0.5f * dryR + 0.5f * wetR;

        widx = (widx + 1) % kBuf;
    }
};

// ============================================================================
// Effect 2b: PHASER  (4-stage all-pass cascade + feedback)
// LFO sweeps the all-pass CORNER FREQUENCY exponentially (in octaves around
// 750 Hz) instead of the raw coefficient -- the old coefficient-domain sweep
// parked the notches above 5 kHz where the EP voices have no energy.
// DEPTH widens the sweep (octaves) and raises feedback; SPEED = LFO rate.
// ============================================================================
struct CpPhaser {
    static constexpr int kStages = 4;
    static constexpr float kTwoPi = 6.28318530717958647692f;

    float sr;
    float phase;
    float phaseR;
    float depthNorm;
    float rateHz;
    float aL, aR;      // cached all-pass coefficients (updated every 8 samples)
    float fb;          // cached feedback amount
    uint32_t cnt;
    float x1L[kStages], y1L[kStages];
    float x1R[kStages], y1R[kStages];
    float lastL, lastR;

    void init(float sr_) {
        sr = sr_;
        reset();
        setDepth(0.5f);
        setSpeed(0.5f);
    }
    void reset() {
        phase = 0.f;
        phaseR = 0.25f * kTwoPi;
        aL = aR = 0.9f;
        fb = 0.2f;
        cnt = 0;
        for (int i = 0; i < kStages; ++i) {
            x1L[i] = y1L[i] = x1R[i] = y1R[i] = 0.f;
        }
        lastL = lastR = 0.f;
    }
    void setDepth(float n) { depthNorm = cp_clamp01(n); }
    void setSpeed(float n) {
        n = cp_clamp01(n);
        rateHz = 0.1f * powf(10.f, n * 1.69897000433601880479f);
    }
    void CP_HOT(process)(float& l, float& r) {
        float inc = kTwoPi * rateHz / sr;
        phase += inc;  if (phase >= kTwoPi) phase -= kTwoPi;
        phaseR += inc; if (phaseR >= kTwoPi) phaseR -= kTwoPi;

        // corner-frequency sweep + coefficient update every 8 samples
        // (exp2f/tan too costly per sample; LFO max 5 Hz, so this is inaudible)
        if ((cnt++ & 7) == 0) {
            float oct = 0.6f + 1.6f * depthNorm;   // sweep width +-0.6..+-2.2 oct
            float fcL = 750.0f * exp2f(oct * g_sinLUT().sin01_nofloor(phase / kTwoPi));
            float fcR = 750.0f * exp2f(oct * g_sinLUT().sin01_nofloor(phaseR / kTwoPi));
            // first-order all-pass corner: a = (1 - tan(pi*fc/sr)) / (1 + tan(pi*fc/sr))
            float tL = fastTan(3.14159265f * fcL / sr);
            float tR = fastTan(3.14159265f * fcR / sr);
            aL = (1.0f - tL) / (1.0f + tL);
            aR = (1.0f - tR) / (1.0f + tR);
            fb = 0.2f + 0.55f * depthNorm;
        }

        float inL = l + fb * fastTanh(lastL);
        float inR = r + fb * fastTanh(lastR);

        float sigL = inL, sigR = inR;
        for (int i = 0; i < kStages; ++i) {
            float yL = -aL * sigL + x1L[i] + aL * y1L[i];
            x1L[i] = sigL; y1L[i] = yL; sigL = yL;
            float yR = -aR * sigR + x1R[i] + aR * y1R[i];
            x1R[i] = sigR; y1R[i] = yR; sigR = yR;
        }
        lastL = sigL;
        lastR = sigR;

        l = 0.5f * l + 0.5f * sigL;
        r = 0.5f * r + 0.5f * sigR;
    }
};

// ============================================================================
// Effect 3: D.DELAY / A.DELAY  (digital vs analog stereo delay)
//   mode 0 = DIGITAL (clean repeats)
//   mode 1 = ANALOG  (BBD-style: EVERY pass into the buffer is lowpassed
//            (~2.5 kHz) and softly saturated, so repeats get progressively
//            darker -- including the first one -- plus a slow clock wobble.
//            The old version filtered only the feedback path, so the first
//            repeat was identical to digital mode and barely distinguishable.)
// ============================================================================
struct CpDelay {
    static constexpr int kBuf = 22080;   // ~500 ms @ 44.1 kHz (was 24001 for 48 kHz)
    static constexpr float kTwoPi = 6.28318530718f;

    float sr;
    int mode;
    float mix;
    float feedback;
    float delaySamp;
    float modPhase;                       // BBD clock wobble LFO (analog mode)
    int16_t bufL[kBuf], bufR[kBuf];   // int16 storage halves RAM (engine source is 16-bit anyway)
    int wIdx;
    float lpL, lpR;

    void init(float sr_) {
        sr = sr_;
        reset();
        setMode(0);
        setDepth(0.5f);
        setTime(0.5f);
    }
    void reset() {
        for (int i = 0; i < kBuf; ++i) { bufL[i] = 0; bufR[i] = 0; }
        wIdx = 0;
        lpL = lpR = 0.f;
        modPhase = 0.f;
    }
    void setMode(int m) { mode = (m == 1) ? 1 : 0; }
    void setDepth(float n) {
        n = cp_clamp01(n);
        mix = n;
        feedback = 0.7f * n;
    }
    void setTime(float n) {
        n = cp_clamp01(n);
        float ms = 20.f + n * (500.f - 20.f);
        delaySamp = ms * 0.001f * sr;
        if (delaySamp > (float)(kBuf - 1)) delaySamp = (float)(kBuf - 1);
    }
    void CP_HOT(process)(float& l, float& r) {
        // BBD clock wobble: +-0.08 % delay-time modulation at 0.9 Hz (analog only)
        modPhase += 0.9f / sr;
        if (modPhase >= 1.f) modPhase -= 1.f;
        float delayEff = delaySamp;
        if (mode == 1) {
            delayEff *= 1.0f + 0.0008f * g_sinLUT().sin01_nofloor(modPhase);
            if (delayEff > (float)(kBuf - 2)) delayEff = (float)(kBuf - 2);
        }

        float rpos = (float)wIdx - delayEff;
        while (rpos < 0.f) rpos += (float)kBuf;
        while (rpos >= (float)kBuf) rpos -= (float)kBuf;
        int i0 = (int)rpos;
        int i1 = i0 + 1; if (i1 >= kBuf) i1 = 0;
        float frac = rpos - (float)i0;
        float sL0 = (float)bufL[i0] * (1.f / 32768.f);
        float sL1 = (float)bufL[i1] * (1.f / 32768.f);
        float sR0 = (float)bufR[i0] * (1.f / 32768.f);
        float sR1 = (float)bufR[i1] * (1.f / 32768.f);
        float dL = sL0 + frac * (sL1 - sL0);
        float dR = sR0 + frac * (sR1 - sR0);

        float wL = l + dL * feedback;
        float wR = r + dR * feedback;
        if (mode == 1) {
            // BBD pass: darken + softly saturate EVERYTHING entering the buffer
            lpL += 0.3f * (wL - lpL);
            lpR += 0.3f * (wR - lpR);
            wL = fastTanh(lpL);
            wR = fastTanh(lpR);
        }

        float cL = wL * 32768.f;
        float cR = wR * 32768.f;
        if (cL > 32767.f) cL = 32767.f; else if (cL < -32768.f) cL = -32768.f;
        if (cR > 32767.f) cR = 32767.f; else if (cR < -32768.f) cR = -32768.f;
        bufL[wIdx] = (int16_t)lrintf(cL);
        bufR[wIdx] = (int16_t)lrintf(cR);
        wIdx++; if (wIdx >= kBuf) wIdx = 0;

        l = l * (1.f - mix) + dL * mix;
        r = r * (1.f - mix) + dR * mix;
    }
};
