// wahwah.h
// Touch wah for the Reface CP chain (header-only, no heap, no exceptions).
// Core: resonant TPT state-variable filter, bandpass-dominant with resonance
// boost (per Reface CP manual: DEPTH = sensitivity, RATE = resonance offset).
// Exponential cutoff sweep for a vocal "quack".
//
// Generated by glm-5.2:cloud, formally reviewed; assembled by the orchestrator.

#pragma once

#include <cmath>
#include <algorithm>
#include <cstdint>
#include "dsp_fastmath.h"
#include "cp_hot.h"

// std::clamp polyfill for pre-C++17
#if !defined(__cpp_lib_clamp) && __cplusplus < 201703L
namespace std {
template <class T>
inline constexpr const T& clamp(const T& v, const T& lo, const T& hi) {
    return (v < lo) ? lo : ((hi < v) ? hi : v);
}
} // namespace std
#endif

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

class SvfWahCore {
public:
    SvfWahCore() { reset(); }
    void setParams(float cutoff, float resoNorm, float sr) {
        cutoff = std::clamp(cutoff, 50.0f, sr * 0.45f);
        resoNorm = std::clamp(resoNorm, 0.0f, 1.0f);
        float Q = 2.5f + 9.5f * resoNorm;
        g = fastTan(float(M_PI) * cutoff / sr);
        k = 1.0f / Q;
        a1 = 1.0f / (1.0f + g * (g + k));
        peakBoost = 1.0f + 3.0f * resoNorm;
    }
    float process(float x) {
        float hp = (x - (k + g) * s1 - s2) * a1;
        float bp = g * hp + s1;
        float lp = g * bp + s2;
        s1 = g * hp + bp;
        s2 = g * bp + lp;
        // bp * k = unity-peak bandpass regardless of Q; lp adds body
        float out = (lp * 0.30f + (bp * k) * peakBoost) * 1.4f;
        return fastTanh(out * 0.7f) / 0.7f;
    }
    void reset() { s1 = s2 = 0.0f; }
private:
    float s1{0.0f}, s2{0.0f};
    float g{0.0f}, k{0.4f}, a1{0.0f};
    float peakBoost{1.0f};
};

class WahWah {
public:
    WahWah() { reset(); }

    void init(float sr) {
        sampleRate = (sr > 0.0f) ? sr : 48000.0f;
        lastFreqL = lastFreqR = 300.0f;
        // one-pole smoothing, ~5 ms, applied once per 8-sample coeff update
        freqSmoothCoeff = 1.0f - std::exp(-8.0f / (sampleRate * 0.005f));
        wahCounter = 0;
    }

    void setMidFreqNorm(float n) {
        midFreqNorm = std::clamp(n, 0.0f, 1.0f);
        _baseFreqCached = mapToLog(midFreqNorm, 200.0f, 450.0f);
        _sweepLogRatio = std::log(2400.0f / _baseFreqCached);
    }

    void setMidGainNorm(float n)    { midGainNorm = std::clamp(n, 0.0f, 1.0f); }
    void setEnvelopeAmount(float n) { envAmount   = std::clamp(n, 0.0f, 1.0f); }

    void CP_HOT(processStereo)(float& inL, float& inR, float envL, float envR) {
        if (envAmount <= 0.01f) return;

        float dryL = inL;
        float dryR = inR;

        // coefficient + sweep update every 8 samples (expf is too costly per sample)
        if ((wahCounter++ & 7) == 0) {
            float curveL = std::sqrt(std::clamp(envL, 0.0f, 1.0f));
            float curveR = std::sqrt(std::clamp(envR, 0.0f, 1.0f));
            // DEPTH = sensitivity: gain applied to the envelope curve, so moderate
            // playing reaches the full sweep at high depth (sweep saturates at 1)
            float sensGain = 0.3f + 2.2f * envAmount;
            float sweepL = std::clamp(curveL * sensGain, 0.0f, 1.0f);
            float sweepR = std::clamp(curveR * sensGain, 0.0f, 1.0f);
            float targetFreqL = _baseFreqCached * std::exp(_sweepLogRatio * sweepL);
            float targetFreqR = _baseFreqCached * std::exp(_sweepLogRatio * sweepR);
            freqSmoothL += freqSmoothCoeff * (targetFreqL - freqSmoothL);
            freqSmoothR += freqSmoothCoeff * (targetFreqR - freqSmoothR);
            lastFreqL = freqSmoothL;
            lastFreqR = freqSmoothR;
            // RATE = resonance offset (per manual); envelope adds a touch on top
            float resoL = std::clamp(midGainNorm + 0.2f * curveL, 0.0f, 1.0f);
            float resoR = std::clamp(midGainNorm + 0.2f * curveR, 0.0f, 1.0f);
            coreL.setParams(freqSmoothL, resoL, sampleRate);
            coreR.setParams(freqSmoothR, resoR, sampleRate);
        }

        float satL = fastTanh(inL * 1.05f) / 1.05f;
        float satR = fastTanh(inR * 1.05f) / 1.05f;

        float wetL = coreL.process(satL);
        float wetR = coreR.process(satR);

        // mostly-wet, envelope-independent mix so the wah never fades away
        float wetMix = 0.55f + 0.40f * envAmount;
        inL = dryL * (1.0f - wetMix) + wetL * wetMix;
        inR = dryR * (1.0f - wetMix) + wetR * wetMix;
    }

    void reset() {
        // NOTE: does NOT touch freqSmoothCoeff/sampleRate — those are set by
        // init() and must survive reset() (chain calls init() then reset()).
        coreL.reset();
        coreR.reset();
        lastFreqL = 300.0f;
        lastFreqR = 300.0f;
        freqSmoothL = 300.0f;
        freqSmoothR = 300.0f;
        wahCounter = 0;
    }

public:
    float lastFreqL{300.0f};
    float lastFreqR{300.0f};

private:
    static float mapToLog(float n, float lo, float hi) {
        n = std::clamp(n, 0.0f, 1.0f);
        return lo * std::exp(std::log(hi / lo) * n);
    }

    SvfWahCore coreL;
    SvfWahCore coreR;

    float sampleRate{44100.0f};
    float midFreqNorm{0.5f};
    float midGainNorm{0.5f};
    float envAmount{1.0f};
    float _baseFreqCached{300.0f};
    float _sweepLogRatio{2.0794f}; // log(2400/300)
    float freqSmoothL{300.0f};
    float freqSmoothR{300.0f};
    float freqSmoothCoeff{0.0f};
    uint32_t wahCounter{0};
};
