// RD_Display.cpp — PicoFaceCP-style page renderer + blocking boot splash.
// Page renderer only paints into the u8g2 full buffer; it MUST NOT call
// u8g2_SendBuffer/FirstPage/NextPage (the main loop streams the buffer out in
// staged half-tile rows via g_ui_flush_row). Only the boot-time splash may block.
// Generated by glm-5.2:cloud, formally reviewed by the orchestrator.
#include "SM_Display.h"
#include "sm_logo.h"

void sm_display_splash(u8g2_t* u) {
    u8g2_ClearBuffer(u);
    u8g2_SetBitmapMode(u, false);
    u8g2_DrawXBMP(u, 0, 0, sm_logoWidth, sm_logoHeight, sm_logo);
    // Blocking send is fine here: audio engine is not running yet.
    u8g2_SendBuffer(u);
}

void sm_display_page(u8g2_t* u, const SmUiModel& m) {
    u8g2_ClearBuffer(u);

    // Header: inverted bar with title (left) and page indicator (right).
    u8g2_SetFontPosBaseline(u);
    u8g2_SetFont(u, u8g2_font_8x13B_tf);
    int hasc = u8g2_GetAscent(u);
    int hdesc = u8g2_GetDescent(u);

    u8g2_SetDrawColor(u, 1);
    u8g2_DrawBox(u, 0, 0, 128, hasc - hdesc);
    u8g2_SetDrawColor(u, 0);

    if (m.title[0] != 0) {
        u8g2_DrawStr(u, 2, hasc, m.title);
    }
    if (m.page[0] != 0) {
        int pw = u8g2_GetStrWidth(u, m.page);
        u8g2_DrawStr(u, 126 - pw, hasc, m.page);
    }

    u8g2_SetDrawColor(u, 1);
    u8g2_DrawHLine(u, 0, hasc - hdesc, 128);

    // Body lines: font 8x13B at (4,32) and (4,48).
    u8g2_SetFont(u, u8g2_font_8x13B_tf);
    if (m.lineA[0] != 0) {
        u8g2_DrawStr(u, 4, 32, m.lineA);
    }
    if (m.lineB[0] != 0) {
        u8g2_DrawStr(u, 4, 48, m.lineB);
    }

    // Footer: font 6x10 at (4,62).
    u8g2_SetFont(u, u8g2_font_6x10_tf);
    if (m.footer[0] != 0) {
        u8g2_DrawStr(u, 4, 62, m.footer);
    }

    // Leave state deterministic for the next pass.
    u8g2_SetDrawColor(u, 1);
    u8g2_SetFont(u, u8g2_font_8x13B_tf);

    // NO SendBuffer here: the main loop streams the buffer out in staged
    // half-tile rows via g_ui_flush_row while audio renders on core 0.
}
