#!/usr/bin/env python3
"""Turn jv_probe dumps into engine calibration tables.

    python3 jv_calibrate.py <dumpdir> > jv_calibration.h

Expects dumps produced by the sweeps described in README.md ("Calibration").
Every measurement is a raw stereo float32 render with note-off at frame
JV_HOLD*32000, so all of this is measured, not modelled.
"""
import glob
import math
import os
import sys

import numpy as np

SR = 32000


def load(path):
    return np.fromfile(path, dtype=np.float32).reshape(-1, 2)


def envelope(x, win):
    return np.sqrt(np.convolve(x ** 2, np.ones(win) / win, "same"))


def fit_pow2(vs, ys):
    """Fit y = a * 2^(v/b); returns (a, b, R^2)."""
    lv, ly = np.array(vs, float), np.log2(np.array(ys, float))
    m, c = np.polyfit(lv, ly, 1)
    r2 = np.corrcoef(lv, ly)[0, 1] ** 2
    return 2 ** c, 1 / m, r2


def release_times(d, hold):
    """Time from note-off to -40 dB, per parameter value."""
    out = []
    for p in sorted(glob.glob(os.path.join(d, "T4_*.f32")),
                    key=lambda s: int(s.rsplit("_", 1)[1].split(".")[0])):
        v = int(p.rsplit("_", 1)[1].split(".")[0])
        e = envelope((lambda a: a[:, 0] + a[:, 1])(load(p))[int(SR * hold):], 64)
        ref = e[:320].mean()
        if ref < 1e-9:
            continue
        db = 20 * np.log10(np.maximum(e, 1e-12) / ref)
        i = int(np.argmax(db < -40))
        if db[i] >= -40:
            continue
        out.append((v, i / SR))
    return out


def attack_times(d, hold):
    """Time from note-on to 98 % of the peak, per parameter value."""
    out = []
    for p in sorted(glob.glob(os.path.join(d, "T1_*.f32")),
                    key=lambda s: int(s.rsplit("_", 1)[1].split(".")[0])):
        v = int(p.rsplit("_", 1)[1].split(".")[0])
        e = envelope((lambda a: a[:, 0] + a[:, 1])(load(p)), 128)
        pk = e[:int(SR * hold)].max()
        if pk < 1e-9:
            continue
        n = int(np.argmax(e >= 0.98 * pk))
        out.append((v, n / SR))
    return out


def emit(name, unit, pairs, fit_range=None, note=""):
    print(f"\n// {name} [{unit}] -- measured")
    if note:
        print(f"// {note}")
    if fit_range:
        sel = [(v, y) for v, y in pairs if fit_range[0] <= v <= fit_range[1] and y > 0]
        if len(sel) > 3:
            a, b, r2 = fit_pow2([v for v, _ in sel], [y for _, y in sel])
            print(f"// fit over v={fit_range[0]}..{fit_range[1]}: "
                  f"{a:.4g} * 2^(v/{b:.2f}), R^2={r2:.4f}")
    print(f"// {'v':>4} {unit:>12}")
    for v, y in pairs:
        print(f"// {v:>4} {y:>12.4f}")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    d = sys.argv[1]
    print("// Generated by tools/jv_extract/jv_calibrate.py -- do not edit by hand.")
    if glob.glob(os.path.join(d, "T4_*.f32")):
        emit("TVA envelope segment time (falling)", "s", release_times(d, 1.0), (8, 127),
             "falling segments decay linearly in dB; this is time to -40 dB")
    if glob.glob(os.path.join(d, "T1_*.f32")):
        emit("TVA envelope segment time (rising)", "s", attack_times(d, 21.0), (16, 112),
             "rising segments ramp linearly in amplitude")
    return 0


if __name__ == "__main__":
    sys.exit(main())
