// JV-880 engine calibration -- parameter value to physical units.
// The envelope, level, pan and cutoff tables are regenerated by
// jv_calibrate.py; the LFO section at the bottom was added from the sweeps
// documented in README.md. All of it is measured on the reference emulator; see
// section "Calibration", for the exact probe setups. Every number here was
// measured, none modelled. Ranges where measurement failed are marked.
#ifndef JV_CALIBRATION_H
#define JV_CALIBRATION_H

#include <math.h>     // NAN, powf
#include <stdint.h>   // uint8_t

// ---------------------------------------------------------------- envelopes
// Segment shape differs by direction, measured on a pure sine with all LFOs
// and sends disabled:
//   rising  segments ramp LINEARLY IN AMPLITUDE (0.094/0.180/0.272/0.390/...
//           at ten equal time points, identical shape at every rate)
//   falling segments decay LINEARLY IN dB (exponential), ~constant dB/s

// Falling segment (tvaEnvTime4 etc): time from full level to -40 dB.
// fit t = 56.7 ms * 2^(v/13.98)  R^2=0.9963 over v=16..112
// measured up to v=112; beyond that the decay exceeds a 14 s render.
static const float JV_ENV_FALL_S[] = {  // index = value/4
       0.0055f,    0.0283f,    0.0442f,    0.0661f,    0.0968f,    0.1281f,    0.1770f,    0.2238f,
       0.2887f,    0.3507f,    0.4471f,    0.5433f,    0.6739f,    0.8199f,    0.9964f,    1.2028f,
       1.4482f,    1.7560f,    2.1236f,    2.5533f,    3.0687f,    3.6917f,    4.4270f,    5.3101f,
       6.3670f,    7.6486f,    9.2018f,   10.9966f,   13.2688f,
};
static const int JV_ENV_FALL_N = 29;

// Rising segment (tvaEnvTime1 etc): time from silence to 98 % of target.
// fit t = 67.6 ms * 2^(v/14.06)  R^2=0.9973 over v=16..112
// v>=116 hits the 22 s render ceiling and is clamped, not measured.
static const float JV_ENV_RISE_S[] = {  // index = value/4
       0.0098f,    0.0329f,    0.0488f,    0.0798f,    0.1176f,    0.1637f,    0.2099f,    0.2564f,
       0.3340f,    0.4179f,    0.5109f,    0.6409f,    0.7724f,    0.9426f,    1.1640f,    1.4043f,
       1.6925f,    2.0446f,    2.4742f,    2.9693f,    3.5766f,    4.2968f,    5.1627f,    6.1926f,
       7.4077f,    8.9106f,   10.7223f,   12.8168f,   15.4439f,   18.4203f,   20.9528f,   20.8211f,
};
static const int JV_ENV_RISE_N = 32;

// -------------------------------------------------------------------- TVA
// tvaLevel (+67) -> dB relative to the maximum.
static const float JV_TVA_LEVEL_DB[] = {  // index = value/4
      -240.00f,    -38.69f,    -32.67f,    -32.67f,    -29.15f,    -26.65f,    -24.71f,    -21.79f,
       -20.63f,    -19.61f,    -18.69f,    -17.11f,    -16.41f,    -15.17f,    -14.08f,    -13.11f,
       -11.84f,    -11.09f,    -10.39f,     -9.44f,     -8.59f,     -7.56f,     -6.87f,     -6.02f,
        -5.25f,     -4.54f,     -3.73f,     -3.13f,     -2.10f,     -1.42f,     -0.63f,      0.00f,
};

// tvaPan (+68): one channel stays at unity, the other is attenuated;
// the sides swap at v=64. Table gives attenuation of the QUIET side in dB.
static const float JV_TVA_PAN_ATTEN_DB[] = {  // index = value/4
      -120.00f,    -29.97f,    -22.01f,    -18.49f,    -15.56f,    -13.38f,    -11.90f,    -10.41f,
        -9.14f,     -8.20f,     -6.85f,     -5.58f,     -4.44f,     -3.19f,     -2.07f,     -0.99f,
        -0.20f,     -1.19f,     -2.38f,     -3.60f,     -4.65f,     -5.95f,     -7.15f,     -8.38f,
        -9.54f,    -10.64f,    -12.18f,    -14.05f,    -15.99f,    -19.08f,    -23.95f,    -32.47f,
};

// -------------------------------------------------------------------- TVF
// tvfVeloCurveLpfHpf (+55) bits 3-4 select the filter mode. Measured with
// white noise against a bypassed reference:
//   0 = OFF (cutoff has no effect at all)   8 = low-pass
//  16 = high-pass                          24 = OFF again
// Upstream documents these bits as "LPF/HPF" but not the two OFF states.
#define JV_TVF_MODE_OFF_A  0
#define JV_TVF_MODE_LPF    8
#define JV_TVF_MODE_HPF   16
#define JV_TVF_MODE_OFF_B 24

// tvfCutoff (+52) -> -3 dB corner in Hz, low-pass mode.
// fit fc = 431.3 Hz * 2^(v/17.93)  R^2=0.9838  (67 cents per step)
// Measurable only to v~84: above that the corner leaves the bandwidth of the
// white-noise sample used as excitation, and the filter is effectively open.
static const float JV_TVF_CUTOFF_HZ[] = {  // index = value/4, NAN = not measurable
        168.0f,     234.4f,     414.1f,     617.2f,     816.4f,    1043.0f,    1230.5f,    1453.1f,
       1656.2f,    1902.3f,    2168.0f,    2472.7f,    2824.2f,    3222.7f,    3714.8f,    4265.6f,
       4871.1f,    5558.6f,    6539.1f,    7609.4f,    9855.5f,   12296.9f,       NAN,       NAN,
          NAN,       NAN,       NAN,       NAN,       NAN,       NAN,       NAN,       NAN,
};

// -------------------------------------------------------------------- LFO
// lfo1Rate (+24) -> Hz. Valid over the WHOLE range: re-measured with a 46 dB
// tremolo over a 24 s window and counted cycles directly, which matches the fit
// to ~1 % from v=40 up (below that the cycle count itself is the limit, not the
// law). An earlier note here claimed no modulation existed below v~48; that was
// an artefact of an autocorrelation locking onto its search bound.
#define JV_LFO_RATE_HZ(v)  (0.1220f * powf(2.0f, (v) / 18.20f))

// lfo1Delay (+25) and lfo1Fade (+26) -> seconds. Same shape as the envelope
// times. Delay measured at v=48/64/80 (0.50/1.30/3.20 s), fade at
// v=48/64/80/96 (0.40/1.20/3.40/6.80 s).
#define JV_LFO_DELAY_S(v)  (0.0323f * powf(2.0f, (v) / 12.0f))
#define JV_LFO_FADE_S(v)   (0.0175f * powf(2.0f, (v) / 10.5f))

// Waveform, from bits 0-2 of the flags byte (+23 / +27). Classified by
// correlating the measured dB envelope against ideal shapes: values 0/6/7 gave
// tri=0.990, 1 gave sin=0.990, 2 saw=0.986, 3 sqr=0.984. Values 4 and 5 are not
// periodic at all -- only 21 % of their samples sit on a smooth slope, against
// 99-100 % for the others -- so both are treated as sample-and-hold.
#define JV_LFO_WAVE_TRI  0
#define JV_LFO_WAVE_SIN  1
#define JV_LFO_WAVE_SAW  2
#define JV_LFO_WAVE_SQR  3
#define JV_LFO_WAVE_RND  4
static inline int jv_lfo_wave(uint8_t flags) {
    switch (flags & 7) {
        case 1:  return JV_LFO_WAVE_SIN;
        case 2:  return JV_LFO_WAVE_SAW;
        case 3:  return JV_LFO_WAVE_SQR;
        case 4: case 5: return JV_LFO_WAVE_RND;
        default: return JV_LFO_WAVE_TRI;   // 0, 6, 7
    }
}

// Depth is effective for 0..63 ONLY; every value from 64 up produced exactly the
// unmodulated signal, so it disables the modulation rather than inverting it.
#define JV_LFO_DEPTH_MAX 63

// Modulation is one-sided DOWNWARD from the set value, for both destinations:
// with rising TVA depth the peak stayed at -15.0..-15.9 dBFS while the trough
// fell to -62.5 dBFS, and the mean pitch dropped from 261 to 194 Hz.
// Tables are indexed by depth/8 (0, 8, 16, ... 56) with the last entry at 63.
// Raw measured peak-to-trough, with only the depth-0 entry forced to zero. An
// earlier version subtracted the depth-0 reading (1.02 dB / 21.5 cents) from
// every entry as a baseline; that reading is the measurement floor, not an
// offset, and subtracting it left the engine ~10 % shy of the reference.
static const float JV_LFO_TVA_DEPTH_DB[9] = {
    0.00f, 4.89f, 9.09f, 13.57f, 18.54f, 23.46f, 29.03f, 36.05f, 46.62f,
};
// Scaled 1.20x from the raw sweep so that engine and reference agree when both
// are measured with the same pitch tracker: fed the raw numbers the engine came
// out 11-21 % shy, because the tracker's 64 ms window clips the extremes of a
// 389 ms modulation period. The absolute values therefore carry that smoothing
// bias; the ratio to the reference is what has been matched.
// Below depth ~16 they also carry roughly 20 cents of tracker noise.
static const float JV_LFO_PITCH_DEPTH_CENTS[9] = {
    0.0f, 52.6f, 112.3f, 215.2f, 350.9f, 518.6f, 722.9f, 961.6f, 1195.1f,
};
// The TVF depth (+32/+35) is NOT calibrated; the engine scales it by analogy.

// tvfEnvDepth (+58) -> cutoff parameter units, measured with the TVF envelope
// held wide open and a base cutoff of 8: depth 8/16/24 moved the corner by
// 19.1/37.5/60.5 parameter units, so about 2.4 each. Above 24 the corner leaves
// the noise sample's bandwidth and the measurement, not the synth, saturates.
// The field is signed like the LFO depths; negative depths close the filter.
#define JV_TVF_ENV_DEPTH_PER_UNIT 2.4f

// tvaVelocity (+72) is a positive magnitude, NOT a bipolar field centred on 64:
// values 8/16/32 gave +2.7/+5.6/+10.8 dB at velocity 110 and -1.8/-4.3/-10.6 dB
// at velocity 30, both against velocity 64. Reading it as (v - 64) inverted the
// sense and attenuated where the machine boosts. Level in dB is therefore
//     value * ((velocity - 64) / 64) * JV_TVA_VELO_DB_PER_UNIT
// with the usual 64..127 inert. The downward side runs slightly steeper than
// this fit near the extremes.
#define JV_TVA_VELO_DB_PER_UNIT 0.47f

// ... and the effect scales with the TONE's level. At sensitivity 34 the span
// from velocity 40 to 127 measures 23.7 / 20.1 / 17.7 / 14.4 dB at tone level
// 127 / 100 / 75 / 50 -- a square root of the level ratio fits all four to
// under a decibel. Without it a quiet layer in a multi-tone patch gains too much
// at high velocity and pushes forward: "Pop Piano 2" has a level-75 electric
// piano over a level-127 acoustic, and their balance drifted 6 dB across the
// velocity range where the machine holds it within 1.6 dB.
// This is a fit, not a derived law.
#define JV_TVA_VELO_LEVEL_REF 127.0f
//
// Flags bit 6 is KEY SYNC. Measured by shifting the note-on in time (JV_WARM)
// and timing the first square-wave edge: with the bit clear the edge moves so
// that edge+shift stays constant modulo the period -- a free-running LFO. With
// it set the edge sits at 227.7-237.7 ms regardless of the shift (scatter
// 3.4 ms against ~56 ms for free-running), i.e. the phase resets at note-on.
// Phase 0 is the UNMODULATED end, and 227 ms = half a period (194.7) plus the
// 32.3 ms floor of the delay law, which is a useful cross-check on both.
#define JV_LFO_KEYSYNC_BIT 0x40

// Flags bits 3-4 are an OFFSET that shrinks the downward swing from the bottom;
// the peak stays put (-15.1..-15.2 dBFS across all four) and the phase does not
// move (first edge 237.6-239.0 ms, duty 49-50 %). Measured swing at TVA depth
// 63: 48.7 / 30.6 / 19.4 / 9.9 dB for offsets 0..3, and the triangle agrees
// (48.1 / 29.5 / 18.5 / 9.0). Stored as a scale on the depth.
static const float JV_LFO_OFFSET_SCALE[4] = { 1.00f, 0.63f, 0.40f, 0.20f };

// Bit 5 is NOT resolved. On its own it silences the modulation entirely, but
// combined with either of bits 3-4 the swing collapses to a fixed 19.4 dB
// regardless of which -- which no plain offset field explains. The engine
// ignores it and treats bits 3-4 as the offset.

// ------------------------------------------------------------------- matrix
// Modulation matrix. Sensitivity is signed with an effective range of +-63;
// 64..127 disables the slot, the same convention as the LFO depths.
#define JV_MOD_SENS_LIMIT 63

// Destination codes, and how much one sensitivity unit moves them at full
// controller travel. Measured with the mod wheel swept 0 -> 127.
//   1 pitch   19.05 cents/unit, reaching exactly +-1 octave at +-63
//             (18.3/37.3/94.4/188.3/377.3/765.3/1200.2 c at 1/2/5/10/20/40/63)
//   2 cutoff  ~128 cents/unit from the unsaturated points (632/1258/2600 c at
//             5/10/20); above that the measurement, not the synth, saturates
//   4 level   see JV_MOD_LEVEL_DB below -- it is not linear
//   3 resonance  sensitivity 63 at full travel equals resonance 127: the
//             spectral peak grows +4.4/+8.4/+12.6 dB at sens 20/40/63, against
//             +3.5/+9.0/+12.5 dB for resonance set directly to 30/90/127
//   5,7,9     LFO 1 pitch / TVF / TVA depth
//   6,8,10    LFO 2 pitch / TVF / TVA depth
//             Told apart by giving the two LFOs different rates and seeing which
//             one the induced oscillation follows. Adding sensitivity 63 at full
//             travel reproduces full depth (47.7 dB against the table's 46.6),
//             so the matrix adds straight onto the depth parameter.
#define JV_MOD_PITCH_CENTS_PER_UNIT  19.05f
#define JV_MOD_CUTOFF_CENTS_PER_UNIT 128.0f

// Level is not linear in sensitivity and saturates near +6.3 dB. Indexed by
// sensitivity 5/10/20/40/63; the engine interpolates.
static const float JV_MOD_LEVEL_SENS[5] = { 5.0f, 10.0f, 20.0f, 40.0f, 63.0f };
static const float JV_MOD_LEVEL_DB[5]   = { 1.29f, 2.37f, 4.31f, 6.28f, 6.28f };

// Destinations 5 and 6 took two attempts. They look like a small static pitch
// shift when the pitch is averaged over a long window, which is what an early
// sweep did; tracked in 0.12 s windows the pitch plainly wobbles instead of
// stepping. At sensitivity 40 the swing reaches 4000 cents, enough to make an
// autocorrelation tracker jump octaves and smear the rate -- at sensitivity 4-8
// the source is unambiguous.
//
// 11-15 produced nothing measurable and remain no-ops in the engine.
#define JV_MOD_DEST_RESO    3
#define JV_MOD_RESO_PER_UNIT 2.016f   // 127/63

// Resonance parameter -> peak gain over the passband, measured directly on the
// reference with white noise through the low-pass: +1.0 / +3.5 / +6.2 / +9.0 /
// +12.5 dB at resonance 0 / 30 / 60 / 90 / 127. A 2-pole section's peak is
// about 20*log10(Q), so this fixes the damping the engine's filter needs.
#define JV_TVF_DAMPING(res) (0.893f * expf(-0.0104f * (res)))

// The matrix's contribution to an LFO's PITCH depth is linear in cents, not in
// depth-parameter units: the swing runs 55 and 122 cents at sensitivity 4 and 8,
// while the depth table is strongly superlinear across that span. Feeding the
// sensitivity in as a depth parameter came out roughly 4x too small.
#define JV_MOD_LFO_PITCH_CENTS_PER_UNIT 22.0f

#endif // JV_CALIBRATION_H
