// JV-880 engine calibration -- parameter value to physical units.
// The envelope, level, pan and cutoff tables are regenerated by
// jv_calibrate.py; the LFO section at the bottom was added from the sweeps
// documented in README.md. All of it is measured on the reference emulator; see
// section "Calibration", for the exact probe setups. Every number here was
// measured, none modelled. Ranges where measurement failed are marked.
#ifndef JV_CALIBRATION_H
#define JV_CALIBRATION_H

#include <math.h>     // NAN, powf
#include <stdint.h>   // uint8_t

// ---------------------------------------------------------------- envelopes
// Segment shape differs by direction, measured on a pure sine with all LFOs
// and sends disabled:
//   rising  segments ramp LINEARLY IN AMPLITUDE (0.094/0.180/0.272/0.390/...
//           at ten equal time points, identical shape at every rate)
//   falling segments decay LINEARLY IN dB (exponential), ~constant dB/s

// Falling segment (tvaEnvTime4 etc): time from full level to -40 dB.
// fit t = 56.7 ms * 2^(v/13.98)  R^2=0.9963 over v=16..112
// measured up to v=112; beyond that the decay exceeds a 14 s render.
static const float JV_ENV_FALL_S[] = {  // index = value/4
       0.0055f,    0.0283f,    0.0442f,    0.0661f,    0.0968f,    0.1281f,    0.1770f,    0.2238f,
       0.2887f,    0.3507f,    0.4471f,    0.5433f,    0.6739f,    0.8199f,    0.9964f,    1.2028f,
       1.4482f,    1.7560f,    2.1236f,    2.5533f,    3.0687f,    3.6917f,    4.4270f,    5.3101f,
       6.3670f,    7.6486f,    9.2018f,   10.9966f,   13.2688f,
};
static const int JV_ENV_FALL_N = 29;

// Rising segment (tvaEnvTime1 etc): time from silence to 98 % of target.
// fit t = 67.6 ms * 2^(v/14.06)  R^2=0.9973 over v=16..112
// v>=116 hits the 22 s render ceiling and is clamped, not measured.
static const float JV_ENV_RISE_S[] = {  // index = value/4
       0.0098f,    0.0329f,    0.0488f,    0.0798f,    0.1176f,    0.1637f,    0.2099f,    0.2564f,
       0.3340f,    0.4179f,    0.5109f,    0.6409f,    0.7724f,    0.9426f,    1.1640f,    1.4043f,
       1.6925f,    2.0446f,    2.4742f,    2.9693f,    3.5766f,    4.2968f,    5.1627f,    6.1926f,
       7.4077f,    8.9106f,   10.7223f,   12.8168f,   15.4439f,   18.4203f,   20.9528f,   20.8211f,
};
static const int JV_ENV_RISE_N = 32;

// -------------------------------------------------------------------- TVA
// Envelope TARGET levels (+75/+77/+79) do NOT follow the tvaLevel curve, which
// the engine assumed at first: the two differ by up to 9.4 dB at low levels.
// Measured by setting every segment time to 0 and every target to the same
// value, so the envelope holds there, then reading the sustained level.
// Above roughly L=32 it is linear at 0.30 dB per unit. Index = value/4, with
// the last entry for 127.
static const float JV_TVA_ENV_LEVEL_DB[33] = {
     -240.00f,   -48.13f,   -42.11f,   -42.11f,   -38.59f,   -36.09f,   -34.15f,   -32.57f,
      -30.07f,   -29.05f,   -27.30f,   -25.85f,   -24.05f,   -23.03f,   -21.28f,   -20.17f,
      -18.88f,   -17.50f,   -16.31f,   -15.07f,   -13.81f,   -12.71f,   -11.48f,   -10.29f,
       -9.05f,    -7.87f,    -6.69f,    -5.52f,    -4.32f,    -3.17f,    -2.02f,    -0.86f,
        0.00f,
};

// tvaPan (+68) does not stop at 127. Swept over the whole byte:
//   0..127   the pan law below
//   128      ALTERNATING -- the balance jumps between 0.119 and 0.768 from one
//            note to the next, which is Roland's "ALT L/R"
//   129..255 centre
// 139 of the 539 active factory tones carry 128, and clamping it to 127 threw
// them hard right with the left channel 39 dB down. "Whistle" has it on all
// four tones, which is why it measured 14 dB quiet.
#define JV_PAN_ALTERNATING 128
#define JV_PAN_ALT_A        15   // pan-equivalent of balance 0.119
#define JV_PAN_ALT_B        98   // ... and of 0.768

// The PATCH-common level (+21) is a third distinct curve, sitting between the
// tone-level and envelope-level ones. Measured by patching the byte and reading
// the sustained level; index = value/16.
static const float JV_PATCH_LEVEL_DB[9] = {
    -240.00f, -35.42f, -25.87f, -19.85f, -14.99f, -10.81f, -7.12f, -3.38f, 0.00f,
};

// Byte +17 of a sample record is NOT a level: patched across its whole range it
// moved the output by 0.00 dB. The engine used to multiply by it through the
// tone-level curve, which wrongly attenuated the 233 of 577 samples that carry
// something other than 127 -- by up to 6.4 dB, and one of them to silence.

// The TVF envelope's levels are a different animal: they scale the cutoff
// excursion and are near-LINEAR in the parameter, not logarithmic. Measured
// with envDepth 24 over a base cutoff of 8, normalised to L=127. Feeding these
// through the dB curve gave 0.09 where the machine gives 0.20 at L=32.
// Index = value/16.
static const float JV_TVF_ENV_LEVEL[9] = {
    0.000f, 0.089f, 0.204f, 0.278f, 0.460f, 0.560f, 0.722f, 0.828f, 1.000f,
};
// tvaLevel (+67) -> dB relative to the maximum.
static const float JV_TVA_LEVEL_DB[] = {  // index = value/4
      -240.00f,    -38.69f,    -32.67f,    -32.67f,    -29.15f,    -26.65f,    -24.71f,    -21.79f,
       -20.63f,    -19.61f,    -18.69f,    -17.11f,    -16.41f,    -15.17f,    -14.08f,    -13.11f,
       -11.84f,    -11.09f,    -10.39f,     -9.44f,     -8.59f,     -7.56f,     -6.87f,     -6.02f,
        -5.25f,     -4.54f,     -3.73f,     -3.13f,     -2.10f,     -1.42f,     -0.63f,      0.00f,
};

// tvaPan (+68): one channel stays at unity, the other is attenuated;
// the sides swap at v=64. Table gives attenuation of the QUIET side in dB.
static const float JV_TVA_PAN_ATTEN_DB[] = {  // index = value/4
      -120.00f,    -29.97f,    -22.01f,    -18.49f,    -15.56f,    -13.38f,    -11.90f,    -10.41f,
        -9.14f,     -8.20f,     -6.85f,     -5.58f,     -4.44f,     -3.19f,     -2.07f,     -0.99f,
        -0.20f,     -1.19f,     -2.38f,     -3.60f,     -4.65f,     -5.95f,     -7.15f,     -8.38f,
        -9.54f,    -10.64f,    -12.18f,    -14.05f,    -15.99f,    -19.08f,    -23.95f,    -32.47f,
};

// -------------------------------------------------------------------- TVF
// tvfVeloCurveLpfHpf (+55) bits 3-4 select the filter mode. Measured with
// white noise against a bypassed reference:
//   0 = OFF (cutoff has no effect at all)   8 = low-pass
//  16 = high-pass                          24 = OFF again
// Upstream documents these bits as "LPF/HPF" but not the two OFF states.
#define JV_TVF_MODE_OFF_A  0
#define JV_TVF_MODE_LPF    8
#define JV_TVF_MODE_HPF   16
#define JV_TVF_MODE_OFF_B 24

// tvfCutoff (+52) -> -3 dB corner in Hz, low-pass mode.
// fit fc = 431.3 Hz * 2^(v/17.93)  R^2=0.9838  (67 cents per step)
// Measurable only to v~84: above that the corner leaves the bandwidth of the
// white-noise sample used as excitation, and the filter is effectively open.
static const float JV_TVF_CUTOFF_HZ[] = {  // index = value/4, NAN = not measurable
        168.0f,     234.4f,     414.1f,     617.2f,     816.4f,    1043.0f,    1230.5f,    1453.1f,
       1656.2f,    1902.3f,    2168.0f,    2472.7f,    2824.2f,    3222.7f,    3714.8f,    4265.6f,
       4871.1f,    5558.6f,    6539.1f,    7609.4f,    9855.5f,   12296.9f,       NAN,       NAN,
          NAN,       NAN,       NAN,       NAN,       NAN,       NAN,       NAN,       NAN,
};

// -------------------------------------------------------------------- LFO
// lfo1Rate (+24) -> Hz. Valid over the WHOLE range: re-measured with a 46 dB
// tremolo over a 24 s window and counted cycles directly, which matches the fit
// to ~1 % from v=40 up (below that the cycle count itself is the limit, not the
// law). An earlier note here claimed no modulation existed below v~48; that was
// an artefact of an autocorrelation locking onto its search bound.
#define JV_LFO_RATE_HZ(v)  (0.1220f * powf(2.0f, (v) / 18.20f))

// lfo1Delay (+25) and lfo1Fade (+26) -> seconds. Same shape as the envelope
// times. Delay measured at v=48/64/80 (0.50/1.30/3.20 s), fade at
// v=48/64/80/96 (0.40/1.20/3.40/6.80 s).
#define JV_LFO_DELAY_S(v)  (0.0323f * powf(2.0f, (v) / 12.0f))
#define JV_LFO_FADE_S(v)   (0.0175f * powf(2.0f, (v) / 10.5f))

// Waveform, from bits 0-2 of the flags byte (+23 / +27). Classified by
// correlating the measured dB envelope against ideal shapes: values 0/6/7 gave
// tri=0.990, 1 gave sin=0.990, 2 saw=0.986, 3 sqr=0.984. Values 4 and 5 are not
// periodic at all -- only 21 % of their samples sit on a smooth slope, against
// 99-100 % for the others -- so both are treated as sample-and-hold.
#define JV_LFO_WAVE_TRI  0
#define JV_LFO_WAVE_SIN  1
#define JV_LFO_WAVE_SAW  2
#define JV_LFO_WAVE_SQR  3
#define JV_LFO_WAVE_RND  4
static inline int jv_lfo_wave(uint8_t flags) {
    switch (flags & 7) {
        case 1:  return JV_LFO_WAVE_SIN;
        case 2:  return JV_LFO_WAVE_SAW;
        case 3:  return JV_LFO_WAVE_SQR;
        case 4: case 5: return JV_LFO_WAVE_RND;
        default: return JV_LFO_WAVE_TRI;   // 0, 6, 7
    }
}

// Depth is effective for 0..63 ONLY; every value from 64 up produced exactly the
// unmodulated signal, so it disables the modulation rather than inverting it.
#define JV_LFO_DEPTH_MAX 63

// Modulation is one-sided DOWNWARD from the set value, for both destinations:
// with rising TVA depth the peak stayed at -15.0..-15.9 dBFS while the trough
// fell to -62.5 dBFS, and the mean pitch dropped from 261 to 194 Hz.
// Tables are indexed by depth/8 (0, 8, 16, ... 56) with the last entry at 63.
// Raw measured peak-to-trough, with only the depth-0 entry forced to zero. An
// earlier version subtracted the depth-0 reading (1.02 dB / 21.5 cents) from
// every entry as a baseline; that reading is the measurement floor, not an
// offset, and subtracting it left the engine ~10 % shy of the reference.
static const float JV_LFO_TVA_DEPTH_DB[9] = {
    0.00f, 4.89f, 9.09f, 13.57f, 18.54f, 23.46f, 29.03f, 36.05f, 46.62f,
};
// Scaled 1.20x from the raw sweep so that engine and reference agree when both
// are measured with the same pitch tracker: fed the raw numbers the engine came
// out 11-21 % shy, because the tracker's 64 ms window clips the extremes of a
// 389 ms modulation period. The absolute values therefore carry that smoothing
// bias; the ratio to the reference is what has been matched.
// Below depth ~16 they also carry roughly 20 cents of tracker noise.
static const float JV_LFO_PITCH_DEPTH_CENTS[9] = {
    0.0f, 52.6f, 112.3f, 215.2f, 350.9f, 518.6f, 722.9f, 961.6f, 1195.1f,
};
// The TVF depth (+32/+35) is NOT calibrated; the engine scales it by analogy.

// tvfEnvDepth (+58) -> cutoff parameter units, measured with the TVF envelope
// held wide open and a base cutoff of 8: depth 8/16/24 moved the corner by
// 19.1/37.5/60.5 parameter units, so about 2.4 each. Above 24 the corner leaves
// the noise sample's bandwidth and the measurement, not the synth, saturates.
// The field is signed like the LFO depths; negative depths close the filter.
#define JV_TVF_ENV_DEPTH_PER_UNIT 2.4f

// tvaVelocity (+72) only ever ATTENUATES, and it attenuates below velocity 127.
// Measured against velocity sensitivity 0 at the SAME velocity -- a comparison
// the first calibration never made:
//
//        velo:      8      16      25      34      48      63
//   at vel 127:  +0.00   +0.00   +0.00   +0.00   +0.00   +0.00
//   at vel 100:  -1.56   -3.10   -4.91   -6.26   -9.07  -11.99
//   at vel  64:  -3.59   -7.52  -11.62  -15.71  -24.42  -45.25
//
// So the loudest note is the same whatever the sensitivity, and the setting
// decides how much quieter softer notes get. The earlier model boosted above
// velocity 64 instead, which was wrong in direction and, because factory
// patches carry sensitivities of 13..42, masked a ~10 dB base level error.
//
// The attenuation tracks the product velo * (127 - velocity) closely: about
// 0.0072 dB per unit up to ~2100, steepening beyond. Table below is that
// product against decibels.
static const float JV_TVA_VELO_PRODUCT[10] = {
    0.0f, 216.0f, 432.0f, 504.0f, 675.0f, 1008.0f, 1575.0f, 2142.0f, 3024.0f, 3969.0f,
};
static const float JV_TVA_VELO_ATTEN_DB[10] = {
    0.0f,   1.56f,  3.10f,  3.59f,  4.91f,   7.52f,  11.62f,  15.71f,  24.42f,  45.25f,
};
//
// Flags bit 6 is KEY SYNC. Measured by shifting the note-on in time (JV_WARM)
// and timing the first square-wave edge: with the bit clear the edge moves so
// that edge+shift stays constant modulo the period -- a free-running LFO. With
// it set the edge sits at 227.7-237.7 ms regardless of the shift (scatter
// 3.4 ms against ~56 ms for free-running), i.e. the phase resets at note-on.
// Phase 0 is the UNMODULATED end, and 227 ms = half a period (194.7) plus the
// 32.3 ms floor of the delay law, which is a useful cross-check on both.
#define JV_LFO_KEYSYNC_BIT 0x40

// Flags bits 3-5 are the OFFSET, a five-valued field the manual gives as
// -100/-50/0/+50/+100. Bit 5 is its top bit, which is why sweeping that bit
// alone never made sense on its own. Measured swing at TVA depth 63:
// 48.7 / 30.6 / 19.4 / 9.9 dB for indices 0..3, the triangle agreeing
// (48.1 / 29.5 / 18.5 / 9.0), and index 4 silencing the modulation outright.
// The peak stays put across all of them (-15.1..-15.2 dBFS) and the phase does
// not move (first edge 237.6-239.0 ms, duty 49-50 %).
//
// What the manual explains is why those numbers fall the way they do. The
// offset shifts the whole waveform rather than resizing it: at -100 it sits
// wholly below the set value, at +100 wholly above. The engine's LFO is
// unipolar DOWNWARD -- 1.0 is the unmodulated value, 0.0 is full modulation --
// so it represents only the half of the swing that goes down. Index 0 (-100)
// is therefore the full excursion, index 4 (+100) has nothing left below the
// carrier and goes silent, and the centred index 2 keeps roughly half. That is
// the 0.40 measured, and it is what the depth tables above are divided by:
// they were measured at index 0, while 536 of the 539 factory tones sit at
// index 2. The two cancel, which is why the depths came out right before this
// field was understood.
//
// Indices 5-7 are not valid settings; they measured as index 2 and are mapped
// there. Only five factory tones use anything but the neutral index 2 at all.
static const float JV_LFO_OFFSET_SCALE[8] = {
    1.00f, 0.63f, 0.40f, 0.20f, 0.00f, 0.40f, 0.40f, 0.40f,
};
#define JV_LFO_OFFSET_NEUTRAL 2

// Bit 7 is the fade POLARITY: clear is fade IN (the LFO ramps up over the fade
// time after the delay), set is fade OUT (it starts at full depth and ramps
// away). Two factory tones use OUT. Bit 6 is key sync, above.
#define JV_LFO_FADEOUT_BIT 0x80

// -------------------------------------------------------------- keyfollows
// Keyfollow fields are packed nibbles that index one of two tables of fixed
// percentages. Which nibble holds which field was settled from the factory
// banks rather than by probing, using the fact that the two tables have
// different lengths and different neutral indices:
//
//   field                  nibble    neutral index   evidence
//   pan keyfollow          +39 high  7  (= 0 %)      446/539 at 7, never 15
//   random pitch           +39 low   0  (= 0 cents)  521/539 at 0
//   pitch keyfollow        +40 low   12 (= +100 %)   507/539 at 12 -- the normal
//                                                    octave per twelve keys, and
//                                                    only the 16-entry table has
//                                                    +100 at index 12
//   P-ENV time keyfollow   +40 high  7                534/539 at 7
//   TVF-ENV time keyfollow +54 high  7                391/539 at 7
//   cutoff keyfollow       +54 low   5  (= 0 %)      354/539 at 5, and 15 occurs
//                                                    (only the 16-entry table
//                                                    reaches that far)
//   TVA level / time KF    +70       7                both nibbles neutral at 7
//
// The two tables are printed in the manual; the indices above are what makes
// them fall into place.
static const float JV_KF15[15] = {   // 0..14, neutral at index 7
    -100.0f, -70.0f, -50.0f, -40.0f, -30.0f, -20.0f, -10.0f, 0.0f,
      10.0f,  20.0f,  30.0f,  40.0f,  50.0f,  70.0f, 100.0f,
};
static const float JV_KF16[16] = {   // 0..15, neutral at index 5
    -100.0f, -70.0f, -50.0f, -30.0f, -10.0f, 0.0f, 10.0f, 20.0f,
      30.0f,  40.0f,  50.0f,  70.0f, 100.0f, 120.0f, 150.0f, 200.0f,
};
static inline float jv_kf15(int nib) { return JV_KF15[nib > 14 ? 14 : (nib < 0 ? 0 : nib)]; }
static inline float jv_kf16(int nib) { return JV_KF16[nib & 15]; }

// Cutoff keyfollow at +100 % means the corner tracks the keyboard one for one.
// The cutoff law is 431.3 Hz * 2^(v/17.93), i.e. 17.93 parameter units per
// octave, so a semitone is 17.93/12 units. This one needs no measurement: it
// falls out of the calibration that is already here.
#define JV_CUTOFF_UNITS_PER_SEMITONE (17.93f / 12.0f)

// Pitch keyfollow at +100 % is the normal semitone per key; the table's other
// entries scale that directly.
// Random pitch (+39 low nibble) in cents, redrawn per note.
static const float JV_RANDOM_PITCH_CENTS[16] = {
    0.0f, 5.0f, 10.0f, 20.0f, 30.0f, 40.0f, 50.0f, 70.0f,
  100.0f, 200.0f, 300.0f, 400.0f, 500.0f, 600.0f, 800.0f, 1200.0f,
};

// PROVISIONAL, not measured. The manual draws both of these as fans over
// roughly C2..C7 about C4, reaching the full excursion at +-100 % at the edges
// of that span -- about 30 semitones each way. Level keyfollow is given the
// same 30-semitone span in dB, sized so that +-100 % spans the same range the
// tone-level control does over its top half. Both are marked so a later sweep
// can replace them; they affect 93 and roughly 100 tones respectively.
#define JV_PAN_KF_UNITS_PER_SEMITONE   (64.0f / 30.0f)
#define JV_LEVEL_KF_DB_PER_SEMITONE    (12.0f / 30.0f)

// PROVISIONAL. Patch-common analog feel (+20), the drift that keeps tones of
// one patch from phase-locking. Neither manual gives a magnitude; 119 of the
// 192 factory patches set it non-zero, most of them low. Ten cents of per-note
// detune at the maximum is enough to break a fixed beat without audibly
// detuning anything. Roland's JV Master Class notes describe it as "irregular
// variations in pitch AND level", so a matching level jitter goes with it.
#define JV_ANALOG_FEEL_CENTS 10.0f
#define JV_ANALOG_FEEL_DB     0.8f

// ------------------------------------------------------------ velocity curves
// TVF (+55 bits 0-2) and TVA (+71 bits 0-2) each pick one of seven shapes that
// warp velocity before the sensitivity law sees it. MEASURED, by forcing a tone
// to a flat sustain with velocity sensitivity 32 and reading its level at nine
// velocities for each of the seven settings.
//
// Two things the sweep settled that guesswork had got wrong. All seven curves
// give exactly the same level at velocity 127 -- that is the anchor, as it is
// for the sensitivity law itself. And stored curve 0 came out as the straight
// line: expressing every curve as "the velocity that curve 0 would need to
// produce the same level" makes curve 0 the exact identity, which is the right
// footing because JV_TVA_VELO_ATTEN_DB above was itself measured on curve 0.
// An earlier version read the shapes off the icons the manual prints and put an
// x^2 law on stored curve 0, which quietly took 3 dB off half the factory
// patches.
//
// Rows are the seven settings, columns the velocities 0, 16, 32, 48, 64, 80,
// 96, 112, 127. Values are effective velocity in curve-0 units. Curves 0-2 are
// the only ones the factory banks use on the TVA (371 / 153 / 15 tones) and
// 0-3 on the TVF; 5 is an S that crosses the diagonal near velocity 64 and 6
// stays nearly flat until the very top.
static const float JV_VELO_CURVE[7][9] = {
    {    0.0f,   16.0f,   32.0f,   48.0f,   64.0f,   80.0f,   96.0f,  112.0f,  127.0f },
    {    0.0f,    8.5f,   13.6f,   19.3f,   30.4f,   46.6f,   65.1f,   92.8f,  127.0f },
    {    0.0f,    0.0f,    8.5f,    8.5f,   11.7f,   16.0f,   30.4f,   65.1f,  127.0f },
    {    0.0f,   42.0f,   66.2f,   82.9f,   95.0f,  105.2f,  113.5f,  121.2f,  127.0f },
    {    0.0f,   81.5f,   96.0f,  105.2f,  112.0f,  116.7f,  120.3f,  124.8f,  127.0f },
    {    0.0f,    8.5f,   11.7f,   19.3f,   65.1f,  109.7f,  120.3f,  124.8f,  127.0f },
    {    0.0f,   46.6f,   55.1f,   59.8f,   64.0f,   68.2f,   72.8f,   82.9f,  127.0f },
};
// The breakpoints are even 16 apart except the last, which spans 112..127.
static inline float jv_velocity_curve(int curve, int vel) {
    if (curve < 0) curve = 0; else if (curve > 6) curve = 6;
    if (vel <= 0) return 0.0f;
    if (vel >= 127) return 127.0f;
    const float* r = JV_VELO_CURVE[curve];
    if (vel >= 112) return r[7] + (r[8] - r[7]) * ((float)(vel - 112) / 15.0f);
    const int i = vel >> 4;
    return r[i] + (r[i + 1] - r[i]) * ((float)(vel - (i << 4)) / 16.0f);
}
// The TVF curve field is assumed to select the same seven shapes -- the manual
// prints the identical set of icons for both -- but only the TVA side has been
// swept.

// --------------------------------------------------- TVF envelope velocity
// tvfVelocity (+56) scales the TVF envelope's depth with velocity. MEASURED by
// holding the envelope wide open over a base cutoff of 8 and reading the
// brightness back as an effective depth, for thirteen sensitivities across
// eight velocities.
//
// The law is linear and simple once the readings are converted back to depth:
//
//     positive sensitivity   f = 1 - (s/32) * (127 - v)/127
//     negative sensitivity   f = 1 - (|s|/32) *  v /127
//
// clamped to 0..1. Fitted over all 96 points to a mean error of 0.010 and a
// worst case of 0.067, and the three worst are all points where the reading
// had already floored while the model still predicts a few percent.
//
// The scale constant is 32, NOT 63. Sensitivity 32 takes the depth to exactly
// zero at velocity 0 and the factory banks go up to 63, i.e. half the range
// saturates within the velocity span. An earlier version divided by 63 by
// analogy with the other bipolar fields and was consequently half as strong as
// the machine everywhere.
//
// Velocity 127 is the pivot for positive sensitivity -- every setting gives the
// full nominal depth there, exactly as the TVA sensitivity law does -- while
// negative sensitivity pivots at velocity 0 instead.
//
// The sweep was run with TVF velocity curve 0, so the velocity handed to this
// must already be warped through jv_velocity_curve.
#define JV_TVF_VELO_FULL_SENS 32.0f
static inline float jv_tvf_velocity_scale(int sens, float vel) {
    if (sens == 0) return 1.0f;
    const float mag = (float)(sens < 0 ? -sens : sens) / JV_TVF_VELO_FULL_SENS;
    const float t = (sens > 0) ? (127.0f - vel) / 127.0f : vel / 127.0f;
    const float f = 1.0f - mag * t;
    return f < 0.0f ? 0.0f : (f > 1.0f ? 1.0f : f);
}

// ---------------------------------------------------------------------- FXM
// Frequency cross modulation (+02: bit 7 switch, bits 0-3 depth 0..15, shown on
// the panel as 1..16). MEASURED by playing the ROM's own sine wave (multisample
// 72) with the filter off and taking the spectrum with FXM off and at ten
// depths, at C3, C4 and C5.
//
// The modulator is a SQUARE WAVE AT A FIXED 125 Hz. The sidebands sit at
// +-125, +-250, +-375, +-500 Hz around the carrier and the spacing does not
// move when the note does -- 125.0 Hz at all three octaves. 125 Hz is the
// sample rate over 256, so this is a plain hardware divider, not something
// derived from the played pitch. (Roland's own JV Master Class notes say FXM
// "uses a square wave to modulate the selected waveform", which is what sent
// the measurement in this direction.)
//
// It modulates FREQUENCY, not phase: the implied modulation index doubles when
// the carrier doubles (0.205 / 0.429 at C3 / C4 for depth 8), so what is
// constant is the FRACTIONAL pitch deviation. That fraction is proportional to
// the panel value:
//
//     k = 0.02167 * (depth + 1)          depth stored 0..15, panel 1..16
//
// i.e. 2.17 % of the playback rate per panel step, alternating sign at 125 Hz.
// Fitted to the ten measured depths within 0.003 (worst case at depth 0, where
// the sidebands are 30 dB down and the reading is noisiest).
#define JV_FXM_RATE_HZ      125.0f
#define JV_FXM_K_PER_STEP   0.02167f
#define JV_FXM_SWITCH_BIT   0x80
#define JV_FXM_DEPTH_MASK   0x0F

// ------------------------------------------------------------------- chorus
// MEASURED by playing the ROM's own white noise (multisample 72 is the sine,
// 74 the noise) with the tone's dry level at 0 and its chorus send at 127, so
// the output IS the chorus, and cross-correlating against a dry render of the
// same note to recover the delay as a function of time.
//
// It is a STEREO MODULATED DELAY. Base delay 578 samples (18.06 ms); the two
// channels modulate in ANTIPHASE, and the minimum sits at 578 for both -- the
// modulation only ever lengthens.
//
//   depth sets the delay SLOPE:  1.738 * (depth + 18) samples per second,
//                                252 at full depth, about 13.6 cents of pitch
//   rate  sets the LFO period:   f = 126 / (183 - 1.344 * rate) Hz,
//                                0.69 Hz at rate 0, 10.2 Hz at 127
//   excursion follows as slope / (2f)
//
// Checked against all sixteen measured rate points and four depth points: the
// model reproduces every excursion to about 2 % (e.g. depth 127 rate 8 gives
// 172 against 172 measured, rate 64 gives 97 against 96, rate 127 gives 12.3
// against 12) and the period is independent of depth, as measured (760 ms at
// rate 64 for every depth).
//
// Level is exactly linear in the parameter: rms/level came out 0.0002464,
// 0.0002464, 0.0002462, 0.0002462, 0.0002448 at level 16..127. Full scale is
// 1.30, not 1.0 -- fitted from a constant 2.26 dB offset against the reference
// that was the same at every depth.
//
// Feedback is a comb: the output rises by 1.000 / 1.014 / 1.055 / 1.145 /
// 1.436 at feedback 0 / 32 / 64 / 96 / 127, which is 1/sqrt(1-g^2) for
// g = 0.72 * fb/127.
#define JV_CHORUS_BASE_DELAY   578.0f
#define JV_CHORUS_SLOPE(depth) (1.738f * ((float)(depth) + 18.0f))
#define JV_CHORUS_RATE_HZ(r)   (126.0f / (183.0f - 1.344f * (float)(r)))
#define JV_CHORUS_FEEDBACK(fb) (0.72f * (float)(fb) / 127.0f)
#define JV_CHORUS_LEVEL_GAIN   1.30f
#define JV_CHORUS_MAX_DELAY    768   // base + the largest excursion, 183 at rate 0
// Bit 7 of the chorus level byte routes the chorus into the REVERB instead of
// the mix; with the reverb level at zero that measured as exact silence.
#define JV_CHORUS_TO_REVERB_BIT 0x80
// Chorus type lives in bits 4-5 of the patch-common reverb/chorus byte. The
// factory banks use CHORUS1 on 170 patches and CHORUS2 on 22; CHORUS3 does not
// occur and measured identical to CHORUS1. CHORUS2 is NOT characterised: its
// output does not correlate with any single delayed copy of the input at any
// lag from 0.3 to 125 ms, so it is not a plain modulated delay. It is given
// CHORUS1's structure here.
#define JV_CHORUS_TYPE1 0
#define JV_CHORUS_TYPE2 1

// ------------------------------------------------------------------- reverb
// Patch common byte +12 holds the reverb type in bits 0-3, +13 the level, +14
// the time, +15 the feedback (the manual calls it "delay feedback", and it does
// nothing for the six reverb algorithms).
//
//   0 ROOM1   1 ROOM2   2 STAGE1   3 STAGE2   4 HALL1   5 HALL2
//   6 DELAY   7 PAN-DLY
//
// Factory use: HALL1 53, PAN-DLY 32, STAGE2 30, HALL2 24, ROOM2 22, STAGE1 13,
// ROOM1 11, DELAY 7.
//
// MEASURED the same way as the chorus -- dry level 0, reverb send 127, chorus
// off -- with a 50 ms burst and a 5 s tail, so the render is essentially the
// impulse response. The reverb output is decorrelated across the channels for
// all six reverb types (|L/R correlation| < 0.04 over the tail).
//
// THE TWO DELAY TYPES ARE EXACT.
//   delay time  = 2.0 + 3.843 * time  ms, measured 2 / 63 / 124 / 185 / 250 /
//                 311 / 372 / 433 / 490 ms at time 0..127 in steps of 16
//   feedback    = fb/128 - 1/64, from the measured per-repeat ratios
//                 0.234 / 0.484 / 0.734 / 0.984 at fb 32 / 64 / 96 / 127
//   PAN-DLY taps at HALF that interval and alternates channels: at time 32 the
//   echoes land at 62 ms left, 124 right, 184 left, 246 right, with the
//   feedback law applying once per pair.
#define JV_REVERB_TYPE_ROOM1   0
#define JV_REVERB_TYPE_ROOM2   1
#define JV_REVERB_TYPE_STAGE1  2
#define JV_REVERB_TYPE_STAGE2  3
#define JV_REVERB_TYPE_HALL1   4
#define JV_REVERB_TYPE_HALL2   5
#define JV_REVERB_TYPE_DELAY   6
#define JV_REVERB_TYPE_PANDLY  7
#define JV_DELAY_MS(time)      (2.0f + 3.843f * (float)(time))
#define JV_DELAY_FEEDBACK(fb)  ((float)(fb) / 128.0f - 1.0f / 64.0f)
#define JV_DELAY_MAX_MS        492.0f
// The delay types pass the signal through, so their full-scale level is much
// higher than the reverb network's: fitted at 0.47 against the reference.
#define JV_DELAY_LEVEL_GAIN    0.609f

// RT60 in milliseconds for the six reverb algorithms, at reverb time 0, 32, 64,
// 96 and 127. Measured by fitting a line to the log decay of the tail between
// -5 and -45 dB. The shapes differ enough that a single law does not fit: the
// room types are close to linear in the parameter while STAGE2 and the halls
// climb steeply at the top, so these are tables and the engine interpolates.
static const float JV_REVERB_TIME_MS[6][5] = {
    {  276.0f,  416.0f,  614.0f,  840.0f, 1124.0f },   // ROOM1
    {  158.0f,  396.0f,  604.0f,  890.0f, 1304.0f },   // ROOM2
    {  237.0f,  429.0f,  652.0f,  918.0f, 1364.0f },   // STAGE1
    {  318.0f,  836.0f, 1354.0f, 2424.0f, 5420.0f },   // STAGE2
    {  524.0f,  800.0f, 1196.0f, 1912.0f, 3583.0f },   // HALL1
    {  404.0f,  761.0f, 1296.0f, 2294.0f, 6572.0f },   // HALL2
};
static const uint8_t JV_REVERB_TIME_POINTS[5] = { 0, 32, 64, 96, 127 };
static inline float jv_reverb_rt60_ms(int type, int time) {
    if (type < 0) type = 0; else if (type > 5) type = 5;
    if (time <= 0) return JV_REVERB_TIME_MS[type][0];
    if (time >= 127) return JV_REVERB_TIME_MS[type][4];
    for (int i = 0; i < 4; i++) {
        const int a = JV_REVERB_TIME_POINTS[i], b = JV_REVERB_TIME_POINTS[i + 1];
        if (time <= b) {
            const float f = (float)(time - a) / (float)(b - a);
            return JV_REVERB_TIME_MS[type][i] +
                   (JV_REVERB_TIME_MS[type][i + 1] - JV_REVERB_TIME_MS[type][i]) * f;
        }
    }
    return JV_REVERB_TIME_MS[type][4];
}
// The algorithm itself is NOT reverse engineered -- what is measured is the
// decay, the stereo decorrelation and the output level. The engine runs a
// Schroeder network sized to hit the measured RT60; it is not the chip's
// topology, and the early-reflection pattern will differ.
// Fitted against the reference on the four commonest types (HALL1, PAN-DLY,
// STAGE2, HALL2 = 139 of 192 patches), which cluster at +27.5 dB before the
// trim. The room types come out a few dB loud: the reference's output level
// falls faster with decay time than a Schroeder network's does, which is one
// more sign that the topology differs.
#define JV_REVERB_LEVEL_GAIN 0.042f

// ------------------------------------------------------------------- matrix
// Modulation matrix. Sensitivity is signed with an effective range of +-63;
// 64..127 disables the slot, the same convention as the LFO depths.
#define JV_MOD_SENS_LIMIT 63

// Destination codes, and how much one sensitivity unit moves them at full
// controller travel. Measured with the mod wheel swept 0 -> 127.
//   1 pitch   19.05 cents/unit, reaching exactly +-1 octave at +-63
//             (18.3/37.3/94.4/188.3/377.3/765.3/1200.2 c at 1/2/5/10/20/40/63)
//   2 cutoff  ~128 cents/unit from the unsaturated points (632/1258/2600 c at
//             5/10/20); above that the measurement, not the synth, saturates
//   4 level   see JV_MOD_LEVEL_DB below -- it is not linear
//   3 resonance  sensitivity 63 at full travel equals resonance 127: the
//             spectral peak grows +4.4/+8.4/+12.6 dB at sens 20/40/63, against
//             +3.5/+9.0/+12.5 dB for resonance set directly to 30/90/127
//   5,7,9     LFO 1 pitch / TVF / TVA depth
//   6,8,10    LFO 2 pitch / TVF / TVA depth
//             Told apart by giving the two LFOs different rates and seeing which
//             one the induced oscillation follows. Adding sensitivity 63 at full
//             travel reproduces full depth (47.7 dB against the table's 46.6),
//             so the matrix adds straight onto the depth parameter.
#define JV_MOD_PITCH_CENTS_PER_UNIT  19.05f
#define JV_MOD_CUTOFF_CENTS_PER_UNIT 128.0f

// Level is not linear in sensitivity and saturates near +6.3 dB. Indexed by
// sensitivity 5/10/20/40/63; the engine interpolates.
static const float JV_MOD_LEVEL_SENS[5] = { 5.0f, 10.0f, 20.0f, 40.0f, 63.0f };
static const float JV_MOD_LEVEL_DB[5]   = { 1.29f, 2.37f, 4.31f, 6.28f, 6.28f };

// Destinations 5 and 6 took two attempts. They look like a small static pitch
// shift when the pitch is averaged over a long window, which is what an early
// sweep did; tracked in 0.12 s windows the pitch plainly wobbles instead of
// stepping. At sensitivity 40 the swing reaches 4000 cents, enough to make an
// autocorrelation tracker jump octaves and smear the rate -- at sensitivity 4-8
// the source is unambiguous.
//
// 11-15 produced nothing measurable and remain no-ops in the engine.
#define JV_MOD_DEST_RESO    3
#define JV_MOD_RESO_PER_UNIT 2.016f   // 127/63

// Resonance parameter -> peak gain over the passband, measured directly on the
// reference with white noise through the low-pass: +1.0 / +3.5 / +6.2 / +9.0 /
// +12.5 dB at resonance 0 / 30 / 60 / 90 / 127. A 2-pole section's peak is
// about 20*log10(Q), so this fixes the damping the engine's filter needs.
#define JV_TVF_DAMPING(res) (0.893f * expf(-0.0104f * (res)))

// The matrix's contribution to an LFO's PITCH depth is linear in cents, not in
// depth-parameter units: the swing runs 55 and 122 cents at sensitivity 4 and 8,
// while the depth table is strongly superlinear across that span. Feeding the
// sensitivity in as a depth parameter came out roughly 4x too small.
#define JV_MOD_LFO_PITCH_CENTS_PER_UNIT 22.0f

#endif // JV_CALIBRATION_H
