#!/usr/bin/env python3
"""Turn a local JV-880 ROM set into something the firmware can embed.

    python3 jv_make_blob.py <romdir> <outdir> [--banks A,B]

Writes into <outdir>:
    jv_wave.bin   descrambled wave data
    jv_rom2.bin   256 KiB of tables and patches
    jv_blob.S     assembly that pulls both in with .incbin

Without --banks the wave file is the full 4 MiB and rom2 is verbatim, which is
the faithful build: every patch of every bank plays.

With --banks the wave file is rebuilt from only the samples those banks reach,
which is what makes the instrument fit a 4 MB Pico 2. See `compact()` for what
that costs and why the sample table has to be rewritten along with it.

The blob is emitted as .incbin rather than a C array on purpose: 4.25 MB of
initialiser list takes minutes to compile and gigabytes of RAM, while .incbin
is a file copy. No ROM data is in this repository -- see README.md.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jv_rom import JvRom, PATCH_BANKS, SAMPLE_STRIDE  # noqa: E402

PAGE = 1 << 20        # the wave address space is paged; see below
NIBBLES = 0x8000      # exponent nibbles occupy the head of every page
CAPACITY = PAGE - NIBBLES

STUB = """// Generated by tools/jv_extract/jv_make_blob.py -- do not edit.
// The JV-880 ROM images live outside the repository; this file only points at
// the copies the build step produced.
    .section .rodata
    .balign 4
    .global jv_wave_blob
    .global jv_wave_blob_end
jv_wave_blob:
    .incbin "{wave}"
jv_wave_blob_end:

    .balign 4
    .global jv_rom2_blob
    .global jv_rom2_blob_end
jv_rom2_blob:
    .incbin "{rom2}"
jv_rom2_blob_end:
"""


def reachable(rom, banks):
    """Sample indices the given patch banks can actually sound.

    A tone names a multisample, the multisample names up to 16 samples across
    its key zones, and every zone is reachable because the split points are
    patch-independent. Tones with bit 7 of the flag byte clear are off and are
    skipped -- that alone accounts for a good part of what falls away.
    """
    multis = set()
    for bank in banks:
        for p in range(64):
            for t in range(4):
                tone = rom.tone(bank, p, t)
                if tone[0] & 0x80:
                    multis.add(tone[1])
    out = set()
    for m in sorted(multis):
        if m < len(rom.multis):
            out.update(rom.multis[m]["samples"])
    return sorted(s for s in out if s < len(rom.samples))


def compact(rom, keep):
    """Rebuild the wave data around `keep`, returning (wave, addr_map).

    Three constraints shape the layout, all of them coming from how the chip
    addresses the exponent nibble for a byte at address a:

        nibble_byte = wave[(a & 0xF00000) | ((a & 0xFFFFF) >> 5)]
        nibble      = high half if a & 0x10 else low half

    so (1) a sample has to keep its address modulo 32 -- move it by anything
    else and it reads its neighbours' exponents; (2) it has to stay inside one
    1 MB page, because that is what supplies its nibbles; and (3) the first
    32 KB of every page are nibbles and cannot hold sample data, which is why a
    page holds 992 KB rather than 1 MB.

    Samples overlap: 577 samples span 4.3 MB of ranges inside a 4 MB ROM, so
    several share a body and differ only in loop points. Moving them
    individually would duplicate roughly half a megabyte, so overlapping ranges
    are merged first and relocated as one block. That is also why blocks cannot
    be split to fill a page: the samples inside them are tied to each other.
    """
    # 32-byte aligned ranges, merged per source page.
    per_page = {}
    for si in keep:
        s = rom.samples[si]
        lo, hi = s["start"] & ~31, (s["end"] | 31) + 1
        if s["start"] // PAGE != s["end"] // PAGE:
            raise SystemExit(f"sample {si} straddles a page boundary")
        per_page.setdefault(s["start"] // PAGE, []).append((lo, hi))

    blocks = []
    for page, spans in sorted(per_page.items()):
        spans.sort()
        for lo, hi in spans:
            if blocks and blocks[-1][0] == page and lo <= blocks[-1][2]:
                blocks[-1] = (page, blocks[-1][1], max(blocks[-1][2], hi))
            else:
                blocks.append((page, lo, hi))

    # First-fit decreasing. Plain sequential packing leaves ~130 KB stranded at
    # the page ends, which is most of the margin the whole exercise buys.
    dest = []   # per destination page: [bytes free, [(src_lo, src_hi, dst_lo)]]
    for _page, lo, hi in sorted(blocks, key=lambda b: b[1] - b[2]):
        n = hi - lo
        for di, d in enumerate(dest):
            if d[0] >= n:
                break
        else:
            dest.append([CAPACITY, []])
            di, d = len(dest) - 1, dest[-1]
        d[1].append((lo, hi, PAGE * di + NIBBLES + (CAPACITY - d[0])))
        d[0] -= n

    wave = bytearray(PAGE * len(dest))
    addr_map = []   # (src_lo, src_hi, delta), sorted, for translating addresses
    for d in dest:
        for lo, hi, dst in d[1]:
            wave[dst:dst + (hi - lo)] = rom.wave[lo:hi]
            # The nibbles for those bytes, one per 32, move with them. Both
            # addresses are 32-aligned, so this is a straight block copy too.
            src_n = (lo & 0xF00000) | ((lo & 0xFFFFF) >> 5)
            dst_n = (dst & 0xF00000) | ((dst & 0xFFFFF) >> 5)
            wave[dst_n:dst_n + (hi - lo) // 32] = rom.wave[src_n:src_n + (hi - lo) // 32]
            addr_map.append((lo, hi, dst - lo))
    addr_map.sort()

    # Trim the trailing unused part of the last page; nothing addresses it.
    end = max(dst + (hi - lo) for d in dest for lo, hi, dst in d[1])
    return bytes(wave[:end]), addr_map


def rewrite_tables(rom2, rom, keep, addr_map):
    """Point the sample table at the new addresses; invalidate what was cut.

    The engine validates every entry it loads (`start < loop <= end`), so a
    dropped sample is disabled simply by zeroing it -- a tone that names one
    falls silent instead of playing whatever now sits at that address.
    """
    out = bytearray(rom2)
    base = rom.sample_table[0]
    kept = set(keep)

    def translate(a):
        for lo, hi, delta in addr_map:
            if lo <= a < hi:
                return a + delta
        raise SystemExit(f"address 0x{a:06x} is not in the compacted blob")

    for i, s in enumerate(rom.samples):
        o = base + i * SAMPLE_STRIDE
        if i not in kept:
            out[o:o + 9] = b"\0" * 9
            continue
        for k, field in enumerate(("start", "loop", "end")):
            out[o + 3 * k:o + 3 * k + 3] = translate(s[field]).to_bytes(3, "big")
    return bytes(out)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    opts = [a for a in sys.argv[1:] if a.startswith("--")]
    if len(args) != 2:
        print(__doc__)
        return 2
    romdir, outdir = args
    banks = None
    for o in opts:
        if o.startswith("--banks="):
            banks = [b.strip() for b in o[len("--banks="):].split(",") if b.strip()]
        else:
            print(f"unknown option {o}", file=sys.stderr)
            return 2
    if banks:
        unknown = [b for b in banks if b not in PATCH_BANKS]
        if unknown:
            print(f"unknown bank(s) {unknown}; known: {list(PATCH_BANKS)}", file=sys.stderr)
            return 1

    os.makedirs(outdir, exist_ok=True)
    for name, size in (("jv880_rom2.bin", 0x40000),
                       ("jv880_waverom1.bin", 0x200000),
                       ("jv880_waverom2.bin", 0x200000)):
        path = os.path.join(romdir, name)
        if not os.path.exists(path) or os.path.getsize(path) != size:
            print(f"{name} missing or not {size} bytes", file=sys.stderr)
            return 1

    rom = JvRom(romdir)
    rom2 = rom.rom2

    if banks:
        keep = reachable(rom, banks)
        wave, addr_map = compact(rom, keep)
        rom2 = rewrite_tables(rom2, rom, keep, addr_map)
        note = (f"banks {'+'.join(banks)}: {len(keep)}/{len(rom.samples)} samples, "
                f"{len(addr_map)} blocks")
    else:
        wave = rom.wave
        note = "full ROM"

    wave_path = os.path.join(outdir, "jv_wave.bin")
    rom2_path = os.path.join(outdir, "jv_rom2.bin")
    open(wave_path, "wb").write(wave)
    open(rom2_path, "wb").write(rom2)
    open(os.path.join(outdir, "jv_blob.S"), "w").write(
        STUB.format(wave=wave_path.replace("\\", "/"), rom2=rom2_path.replace("\\", "/"))
    )
    print(f"jv_make_blob: {len(wave) / 1024 / 1024:.2f} MB wave + "
          f"{len(rom2) / 1024:.0f} KB rom2 ({note}) -> {outdir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
