#!/usr/bin/env python3
"""Turn a local JV-880 ROM set into something the firmware can embed.

    python3 jv_make_blob.py <romdir> <outdir>

Writes into <outdir>:
    jv_wave.bin   4 MiB, both wave ROMs descrambled and concatenated
    jv_rom2.bin   256 KiB, verbatim (it holds the tables, not sample data)
    jv_blob.S     assembly that pulls both in with .incbin

The blob is emitted as .incbin rather than a C array on purpose: 4.25 MB of
initialiser list takes minutes to compile and gigabytes of RAM, while .incbin
is a file copy. No ROM data is in this repository -- see README.md.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jv_rom import descramble  # noqa: E402

STUB = """// Generated by tools/jv_extract/jv_make_blob.py -- do not edit.
// The JV-880 ROM images live outside the repository; this file only points at
// the copies the build step produced.
    .section .rodata
    .balign 4
    .global jv_wave_blob
    .global jv_wave_blob_end
jv_wave_blob:
    .incbin "{wave}"
jv_wave_blob_end:

    .balign 4
    .global jv_rom2_blob
    .global jv_rom2_blob_end
jv_rom2_blob:
    .incbin "{rom2}"
jv_rom2_blob_end:
"""


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    romdir, outdir = sys.argv[1], sys.argv[2]
    os.makedirs(outdir, exist_ok=True)

    rom2 = open(os.path.join(romdir, "jv880_rom2.bin"), "rb").read()
    if len(rom2) != 0x40000:
        print(f"jv880_rom2.bin is {len(rom2)} bytes, expected 262144", file=sys.stderr)
        return 1

    wave = bytearray()
    for name in ("jv880_waverom1.bin", "jv880_waverom2.bin"):
        raw = open(os.path.join(romdir, name), "rb").read()
        if len(raw) != 0x200000:
            print(f"{name} is {len(raw)} bytes, expected 2097152", file=sys.stderr)
            return 1
        # A cached descrambled copy may already exist next to the ROMs.
        cached = os.path.join(romdir, "Cache", name)
        wave += open(cached, "rb").read() if os.path.exists(cached) else descramble(raw)

    wave_path = os.path.join(outdir, "jv_wave.bin")
    rom2_path = os.path.join(outdir, "jv_rom2.bin")
    open(wave_path, "wb").write(bytes(wave))
    open(rom2_path, "wb").write(rom2)
    open(os.path.join(outdir, "jv_blob.S"), "w").write(
        STUB.format(wave=wave_path.replace("\\", "/"), rom2=rom2_path.replace("\\", "/"))
    )
    print(f"jv_make_blob: {len(wave) / 1024 / 1024:.2f} MB wave + "
          f"{len(rom2) / 1024:.0f} KB rom2 -> {outdir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
